### ISSUE TITLE
[Bug] (TBC Classic) Not working with Character panel, Spellbook, Talent Panel and Social Panel

### ISSUE THREAD

**Issue by LunaLambda** [Gethe/Aurora#1]
**Describe the bug**
It doesn't work with Character panel, Spellbook, Talent Panel and Social Panel.
I disabled all other addons and only kept Aurora but those panels listed above still doesn't work. 

**To Reproduce**
1. Only install Aurora
2. Launch WoW TBC Classic Ver: 2.5.2.40260

**Comment by TheKronzo** [comment]
this is happening to me too
