### ISSUE TITLE
[Bug] Errors in 10.1.5

### ISSUE THREAD

**Issue by Diagonet** [Gethe/Aurora#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

First 2 errors I get when loading the game
`6x ...urora/SkinBlizzard_Collections.lua:441: attempt to call method 'SetTexCoord' (a nil value)
[string "@Aurora/SkinBlizzard_Collections.lua"]:441: in function `WardrobeItemsModelTemplate'
[string "@Aurora/SkinBlizzard_Collections.lua"]:743: in function `addonModule'
[string "@Aurora/Skin/init.lua"]:185: in function <Aurora/Skin/init.lua:149>
[string "=[C]"]: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:11532: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:11548: in function `BlizzardAPIHook'
[string "@ArkInventory/Core/ArkInventory.lua"]:3169: in function <ArkInventory/Core/ArkInventory.lua:3135>
[string "=[C]"]: ?
[string "@ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:66: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:61>
[string "@ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:523: in function `EnableAddon'
[string "@ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:626: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:175: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:168: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:163: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:154: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:150>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:118: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
DressUpModel = DressUpModel {
 0 = <userdata>
 OnEnter = <function> defined @Blizzard_Collections/Blizzard_Wardrobe.lua:2654
 NewGlow = Texture {
 }
 Border = Texture {
 }
 OnUpdate = <function> defined @Blizzard_Collections/Blizzard_Wardrobe.lua:2690
 TransmogStateTexture = Texture {
 }
 OnShow = <function> defined @Blizzard_Collections/Blizzard_Wardrobe.lua:2733
 checkMarkAnchorY = 0
 CheckTrackableClick = <function> defined @FrameXML/ContentTracking/ContentTrackingElement.lua:46
 checkMarkAnchor = "BOTTOMRIGHT"
 _auroraBD = Frame {
 }
 GetSourceInfoForTracking = <function> defined @Blizzard_Collections/Blizzard_Wardrobe.lua:2579
 Favorite = Frame {
 }
 ClearTrackables = <function> defined @FrameXML/ContentTracking/ContentTrackingElement.lua:36
 SetTrackingCheckmarkShown = <function> defined @FrameXML/ContentTracking/ContentTrackingElement.lua:100
 SetDesaturated = <function> defined @Blizzard_Collections/Blizzard_Wardrobe.lua:2703
 OnMouseDown = <function> defined @Blizzard_Collections/Blizzard_Wardrobe.lua:2597
 HasTrackableSource = <function> defined @FrameXML/ContentTracking/ContentTrackingElement.lua:88
 NewString = FontString {
 }
 checkMarkAnchorX = -3
 OnLeave = <function> defined @Blizzard_Collections/Blizzard_Wardrobe.lua:2684
 OnLoad = <function> defined @Blizzard_Collections/Blizzard_Wardrobe.lua:2537
 OnHide = <function> defined @FrameXML/ContentTracking/ContentTrackingElement.lua:17
 OnModelLoaded = <function> defined @Blizzard_Collections/Blizzard_Wardrobe.lua:2546
 desaturated = false
 Reload = <function> defined @Blizzard_Collections/Blizzard_Wardrobe.lua:2710
 UpdateContentTracking = <function> defined @Blizzard_Collections/Blizzard_Wardrobe.lua:2553
 UpdateTrackingDisabledOverlay = <function> defined @Blizzard_Collections/Blizzard_Wardrobe.lua:2569
 DisabledOverlay = Texture {
 }
 SetTrackable = <function> defined @FrameXML/ContentTracking/ContentTrackingElement.lua:21
 SlotInvalidTexture = Texture {
 }
 AddTrackable = <function> defined @FrameXML/ContentTracking/ContentTrackingElement.lua:26
 UpdateTrackingCheckmark = <function> defined @FrameXML/ContentTracking/ContentTrackingElement.lua:72
 HideVisual = Frame {
 }
}
bg = Texture {
 0 = <userdata>
}
_ = Texture {
 0 = <userdata>
}
_ = Texture {
 0 = <userdata>
}
_ = Texture {
 0 = <userdata>
}
_ = Texture {
 0 = <userdata>
}
highlight = FontString {
 0 = <userdata>
}
bd = Frame {
 BottomLeftCorner = Texture {
 }
 OnBackdropLoaded = <function> defined @Aurora/Skin/backdrop.lua:175
 GetBackdropColor = <function> defined @Aurora/Skin/backdrop.lua:285
 SetBackdropOptions = <function> defined @Aurora/Skin/backdrop.lua:364
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 GetBackdropTexture = <function> defined @Aurora/Skin/backdrop.lua:333
 ApplyBackdrop = <function> defined @Aurora/Skin/backdrop.lua:193
 SetBackdrop = <function> defined @Aurora/Skin/backdrop.lua:246
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 GetBackdropBorderColor = <function> defined @Aurora/Skin/backdrop.lua:305
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 SetBackdropGradient = <function> defined @Aurora/Skin/backdrop.lua:311
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 SetBackdropOption = <function> defined @Aurora/Skin/backdrop.lua:342
 SetBackdropLayer = <function> defined @Aurora/Skin/backdrop.lua:319
 backdropInfo = <table> {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 TopRightCorner = Texture {
 }
 GetBackdropOption = <function> defined @Aurora/Skin/backdrop.lua:358
 GetEdg`

But could be related to arkinventory, thought I disabled bag skinning.

Next one seems to be related with MDT (Mythic dungeon tools)
`6x ...rora/SkinBlizzard_ChallengesUI.lua:114: attempt to index field 'Affixes' (a nil value)
[string "@Aurora/SkinBlizzard_ChallengesUI.lua"]:114: in function `addonModule'
[string "@Aurora/Skin/init.lua"]:185: in function <Aurora/Skin/init.lua:149>
[string "=[C]"]: in function `LoadAddOn'
[string "@MythicDungeonTools/MythicDungeonTools.lua"]:240: in function <...aceMythicDungeonTools/MythicDungeonTools.lua:239>

Locals:
ChallengesKeystoneFrame = ChallengesKeystoneFrame {
 0 = <userdata>
 Instructions = FontString {
 }
 ShowKeystoneFrame = <function> defined @Blizzard_ChallengesUI/Blizzard_ChallengesUI.lua:657
 GetBackdropColor = <function> defined @Aurora/Skin/backdrop.lua:285
 SetBackdropOptions = <function> defined @Aurora/Skin/backdrop.lua:364
 RuneR = Texture {
 }
 RightEdge = Texture {
 }
 RuneBR = Texture {
 }
 RuneCircleL = Texture {
 }
 GlowBurstLarge = Texture {
 }
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 RunesSmallAnim = AnimationGroup {
 }
 InstructionBackground = Texture {
 }
 PulseAnim = AnimationGroup {
 }
 SetBackdropGradient = <function> defined @Aurora/Skin/backdrop.lua:311
 SlotBG = Texture {
 }
 RuneCircleR = Texture {
 }
 RuneCircleBR = Texture {
 }
 OnMouseUp = <function> defined @Blizzard_ChallengesUI/Blizzard_ChallengesUI.lua:651
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 RuneL = Texture {
 }
 LargeRuneGlow = Texture {
 }
 SmallCircleGlow = Texture {
 }
 OnLoad = <function> defined @Blizzard_ChallengesUI/Blizzard_ChallengesUI.lua:596
 TopEdge = Texture {
 }
 GlowBurstSmall = Texture {
 }
 baseStates = <table> {
 }
 RuneBG = Texture {
 }
 InsertedAnim = AnimationGroup {
 }
 SetBackdropColor = <function> defined @Aurora/Skin/backdrop.lua:275
 LeftEdge = Texture {
 }
 Shockwave = Texture {
 }
 Divider = Texture {
 }
 KeystoneSlot = Button {
 }
 RuneBL = Texture {
 }
 TimeLimit = FontString {
 }
 SetBackdropBorderColor = <function> defined @Aurora/Skin/backdrop.lua:289
 RunesSmallRotateAnim = AnimationGroup {
 }
 RunesLargeRotateAnim = AnimationGroup {
 }
 RuneCircleT = Texture {
 }
 RunesLarge = Texture {
 }
 Center = Texture {
 }
 BottomEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Aurora/Skin/backdrop.lua:193
 DungeonName = FontString {
 }
 BottomRightCorner = Texture {
 }
 BottomLeftCorner = Texture {
 }
 GetBackdropBorderColor = <function> defined @Aurora/Skin/backdrop.lua:305
 RuneCircleBL = Texture {
 }
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 SmallRuneGlow = Texture {
 }
 backdropInfo = <table> {
 }
 _backdropInfo = <table> {
 }
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 GetBackdropLayer = <function> defined @Aurora/Skin/backdrop.lua:328
 SetBackdropOption = <function> defined @Aurora/Skin/backdrop.lua:342
 Shockwave2 = Texture {
 }
 GetBackdropTexture = <function> defined @Aurora/Skin/backdrop.lua:333
 CreateAndPositionAffixes = <function> defined @Blizzard_ChallengesUI/Blizzard_ChallengesUI.lua:661
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 SetBackdrop = <function> defined @Aurora/Skin/backdrop.lua:246
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 KeystoneFrame = Texture {
 }
 OnKeystoneSlotted = <function> defined =[C]:-1
 StartChallengeMode = <function> defined @Blizzard_ChallengesUI/Blizzard_ChallengesUI.lua:732
 KeystoneSlotGlow = Texture {
 }
 OnBackdropLoaded = <function> defined @Aurora/Skin/backdrop.lua:175
 GetBackdropOption = <function> defined @Aurora/Skin/backdrop.lua:358
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 RuneT = Texture {
 }
 RunesSmall = Texture {
 }
 SetBackdropLayer = <function> defined @Aurora/Skin/backdrop.lua:319
 StartButton = Button {
 }
 OnHide = <function> defined @Blizzard_ChallengesUI/Blizzard_ChallengesUI.lua:616
 BgBurst2 = Texture {
 }
 OnShow = <function> defined @Blizzard_ChallengesUI/Blizzard_ChallengesUI.lua:609
 Affixes = <table> {
 }
 PowerLevel = FontString {
 }
 CloseButton = Button {
 }
 OnKeystoneRe`

Lastly this one just happens when opening the LFG pvp tab:
`6x ...eAurora/Skin/FrameXML/LFGFrame.lua:19: attempt to index field '_auroraBorder' (a nil value)
[string "@Aurora/Skin/FrameXML/LFGFrame.lua"]:19: in function <...eAurora/Skin/FrameXML/LFGFrame.lua:14>
[string "=[C]"]: in function `LFG_SetRoleIconIncentive'
[string "@Blizzard_PVPUI/Blizzard_PVPUI.lua"]:227: in function `PVPUIFrame_UpdateRoleShortages'
[string "@Blizzard_PVPUI/Blizzard_PVPUI.lua"]:638: in function `HonorFrame_SetType'
[string "@Blizzard_PVPUI/Blizzard_PVPUI.lua"]:548: in function <Blizzard_PVPUI/Blizzard_PVPUI.lua:531>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@FrameXML/PVEFrame.lua"]:120: in function <FrameXML/PVEFrame.lua:91>
[string "=[C]"]: in function `PVEFrame_ShowFrame'
[string "@FrameXML/PVEFrame.lua"]:163: in function <FrameXML/PVEFrame.lua:161>

Locals:
roleButton = Button {
 0 = <userdata>
 permDisabledTip = "Your class may not perform this role."
 lockedIndicator = Frame {
 }
 EdgePulse = Texture {
 }
 shortageBorder = Texture {
 }
 role = "TANK"
 RestartRoleShortagePulseAnim = <function> defined @FrameXML/LFGFrame.lua:2233
 IconPulse = Texture {
 }
 CancelPulseEffect = <function> defined @FrameXML/LFGFrame.lua:2248
 onClick = <function> defined @Blizzard_PVPUI/Blizzard_PVPUI.lua:197
 OnShow = <function> defined @FrameXML/LFGFrame.lua:2209
 OnLoad = <function> defined @FrameXML/LFGFrame.lua:2198
 OnHide = <function> defined @FrameXML/LFGFrame.lua:2213
 enableAnim = false
 RoleShortagePulseModelScene = ModelScene {
 }
 RoleShortagePulseAnim = AnimationGroup {
 }
 checkButton = CheckButton {
 }
 TryPlayPulseEffect = <function> defined @FrameXML/LFGFrame.lua:2238
 EnableRoleShortagePulseAnim = <function> defined @FrameXML/LFGFrame.lua:2222
 incentiveIcon = Frame {
 }
 alert = Frame {
 }
 SetUpIconPulseAnim = <function> defined @FrameXML/LFGFrame.lua:2217
}
incentiveIndex = nil
roleIcon = Texture {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = "attempt to index field '_auroraBorder' (a nil value)"
Color = <table> {
 highlight = <table> {
 }
 cyan = <table> {
 }
 Lightness = <function> defined @Aurora/Skin/color.lua:190
 grayLight = <table> {
 }
 ruby = <table> {
 }
 Saturation = <function> defined @Aurora/Skin/color.lua:169
 button = <table> {
 }
 orange = <table> {
 }
 red = <table> {
 }
 Hue = <function> defined @Aurora/Skin/color.lua:141
 magenta = <table> {
 }
 blue = <table> {
 }
 frame = <table> {
 }
 white = <table> {
 }
 Create = <function> defined @Aurora/Skin/color.lua:111
 jade = <table> {
 }
 grayDark = <table> {
 }
 violet = <table> {
 }
 black = <table> {
 }
 green = <table> {
 }
 lime = <table> {
 }
 yellow = <table> {
 }
 marine = <table> {
 }
 gray = <table> {
 }
}
`

**Comment by arnvid** [comment]
Workaround coming
