### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by xGriinch** [Gethe/Aurora#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

Message: .../AddOns/Aurora/Skin/Interface/FrameXML/PetStable.lua:88: attempt to index field 'PetStableModel' (a nil value)
Time: Fri Sep 22 02:46:10 2023
Count: 1
Stack: .../AddOns/Aurora/Skin/Interface/FrameXML/PetStable.lua:88: attempt to index field 'PetStableModel' (a nil value)
[string "@Interface/AddOns/Aurora/Skin/Interface/FrameXML/PetStable.lua"]:88: in function `?'
[string "@Interface/AddOns/Aurora/Skin/init.lua"]:165: in function <Interface/AddOns/Aurora/Skin/init.lua:149>

Locals: PetStableFrame = PetStableFrame {
 0 = <userdata>
 LeftInset = PetStableLeftInset {
 }
 page = 1
 PetStableModelScene = PetStableModelScene {
 }
 SetBorder = <function> defined =[C]:-1
 layoutType = "PortraitFrameTemplate"
 BottomInset = PetStableBottomInset {
 }
 SetPortraitShown = <function> defined @Interface/SharedXML/PortraitFrame.lua:102
 SetFrameLevelsFromBaseLevel = <function> defined @Interface/SharedXML/PortraitFrame.lua:120
 SetPortraitToBag = <function> defined @Interface/SharedXML/PortraitFrame.lua:80
 SetPortraitAtlasRaw = <function> defined @Interface/SharedXML/PortraitFrame.lua:88
 SetPortraitToUnit = <function> defined @Interface/SharedXML/PortraitFrame.lua:76
 Inset = PetStableFrameInset {
 }
 SetPortraitTexCoord = <function> defined @Interface/SharedXML/PortraitFrame.lua:98
 PortraitContainer = Frame {
 }
 SetPortraitTextureRaw = <function> defined @Interface/SharedXML/PortraitFrame.lua:84
 SetTitleFormatted = <function> defined @Interface/SharedXML/PortraitFrame.lua:40
 SetPortraitToClassIcon = <function> defined @Interface/SharedXML/PortraitFrame.lua:92
 TopTileStreaks = Texture {
 }
 Bg = PetStableFrameBg {
 }
 TitleContainer = Frame {
 }
 SetPortraitToAsset = <function> defined @Interface/SharedXML/PortraitFrame.lua:72
 SetTitleMaxLinesAndHeight = <function> defined @Interface/SharedXML/PortraitFrame.lua:49
 SetTitleColor = <function> defined @Interface/SharedXML/PortraitFrame.lua:32
 CloseButton = PetStableFrameCloseButton {
 }
 NineSlice = Frame {
 }
 GetTitleText = <function> defined @Interface/SharedXML/PortraitFrame.lua:28
 SetTitleOffsets = <function> defined @Interface/SharedXML/PortraitFrame.lua:54
 GetPortrait = <function> defined @Interface/SharedXML/PortraitFrame.lua:63
 SetTitle = <function> defined @Interface/SharedXML/PortraitFrame.lua:36
 SetPortraitTextureSizeAndOffset = <function> defined @Interface/SharedXML/PortraitFrame.lua:106
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = Frame {
 BottomLeftCorner = Texture {
 }
 OnBackdropLoaded = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:175
 GetBackdropColor = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:285
 SetBackdropOptions = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:364
 SetBackdropBorderColor = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:289
 RightEdge = Texture {
 }
 GetBackdropTexture = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:333
 BottomEdge = Texture {
 }
 SetBackdrop = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:246
 GetCenterColor = <function> defined @Interface/SharedXML/NineSlice.lua:285
 GetBackdropBorderColor = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:305
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 SetBackdropGradient = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:311
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 SetBackdropOption = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:342
 SetCenterColor = <function> defined @Interface/SharedXML/NineSlice.lua:278
 backdropInfo = <table> {
 }
 _auroraNineSlice = true
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 TopLeftCorner = Texture {
 }
 SetVertexColor = <function> defined @Interface/SharedXML/NineSlice.lua:315
 SetBorderColor = <function> defined @Interface/SharedXML/NineSlice.lua:292
 SetupTextureC

### Steps To Reproduce

Its basically happening everytime I log into the game. I don't know if one of of my other addons is interfering with it or what it is. 

### Additional context

Addons being used:
BtWQuests
Immersion
Bagnon
Hekili

**Comment by arnvid** [comment]
As a work around you can wrap the PetStableModel with... this is not a proper fix.. but it will atleast let you get to the next part.
`
    if not PetStableModel == nil then
        _G.PetStableModel:SetPoint("TOPLEFT", PetStableFrame.Inset)
        _G.PetStableModel:SetPoint("BOTTOMRIGHT", PetStableFrame.Inset)
        _G.PetStableModelRotateLeftButton:Hide()
        _G.PetStableModelRotateRightButton:Hide()
        _G.PetStableModelShadow:Hide()     
    end

`

**Comment by nForehand** [comment]
I'm having the same issue as xGriinch, even with all other addons disabled

**Comment by arnvid** [comment]
This one we have a proper fix for. Will be merged to main repo soon.
