### ISSUE TITLE
[Bug] Wrath files not in package

### ISSUE THREAD

**Issue by Jeremy7600** [Gethe/Aurora#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Wrath Classic

### Current Behavior

On load you get errors for the files being missing. 

Skin\Interface\FrameXML\FrameXML_Wrath.xml
Skin\Interface\AddOns\AddOns_Wrath.xml

Interface under Skin is does not exist in the Wrath package. There is no FrameXML_Wrath.xml in the Wrath package. 
There is no AddOns_Wrath.xml in the Wrath package.

Further, there is no SharedXML folder in the Wrath package. 

### Expected Behavior

Addon loads and works. 

### Steps To Reproduce

Load game.
Errors presented at login.

**Comment by arnvid** [comment]
Closing this for now - am working on redoing the Classic/SOD/etc implementation. But for now I have disabled the packaging of these modules and closing the tickets related to this. Sorry I cannot update anymore at this time.  The wow-ui-sources are getting more in-line to make this a reality and thus why I am working on a restructure of all of these things.
