### ISSUE TITLE
[Bug] Not working with 10.2

### ISSUE THREAD

**Issue by Heregellas** [Gethe/Aurora#105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail 10.2

### Current Behavior

Hello,

The add-on is not working at all since today's patch 10.2.
Here are some lua errors to give indications : 

**Error 1**

Message: .../Skin/Interface/SharedXML/SharedUIPanelTemplates.lua:766: attempt to index local 'Frame' (a nil value)
Time: Wed Nov  8 14:25:05 2023
Count: 1
Stack: .../Skin/Interface/SharedXML/SharedUIPanelTemplates.lua:766: attempt to index local 'Frame' (a nil value)
[string "@Interface/AddOns/Aurora/Skin/Interface/SharedXML/SharedUIPanelTemplates.lua"]:766: in function `MaximizeMinimizeButtonFrameTemplate'
[string "@Interface/AddOns/Aurora/Skin/Interface/FrameXML/DressUpFrames.lua"]:70: in function `?'
[string "@Interface/AddOns/Aurora/Skin/init.lua"]:165: in function <Interface/AddOns/Aurora/Skin/init.lua:149>

Locals: Frame = nil
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = "MaximizeButton"
 2 = "MinimizeButton"
}
(for control) = 1
_ = 1
name = "MaximizeButton"
(*temporary) = 1
(*temporary) = "MaximizeButton"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'Frame' (a nil value)"
Skin = <table> {
 AchievementHeaderStatusBarTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/AddOns/Blizzard_AchievementUI.lua:226
 LFGSpecificChoiceTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/FrameXML/LFGFrame.lua:129
 GuildChallengeAlertFrameTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/FrameXML/AlertFrameSystems.lua:219
 PopupButtonTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/FrameXML/ItemButtonTemplate.lua:273
 PetBattleUnitTooltipAuraTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/AddOns/Blizzard_PetBattleUI.lua:86
 AuctionHouseAuctionsFrameTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/AddOns/Blizzard_AuctionHouseUI.lua:396
 AuctionHouseItemDisplayBaseTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/AddOns/Blizzard_AuctionHouseUI.lua:170
 AchievementAlertFrameTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/FrameXML/AlertFrameSystems.lua:121
 UnitPopupVoiceToggleButtonTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/FrameXML/UnitPopupCustomControls.lua:15
 InputBoxInstructionsTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/SharedXML/SharedUIPanelTemplates.lua:708
 ComparisonPlayerTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/AddOns/Blizzard_AchievementUI.lua:305
 OptionsListButtonTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/SharedXML/DeprecatedTemplates.lua:52
 MoneyInputFrameTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/FrameXML/MoneyInputFrame.lua:16
 HybridScrollBarTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/SharedXML/HybridScrollFrame.lua:29
 ChannelButtonHeaderTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/AddOns/Blizzard_Channels.lua:49
 QuickJoinToastTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/FrameXML/QuickJoinToast.lua:34
 ContainerFrameHelpBoxTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/FrameXML/ContainerFrame.lua:77
 MultiBar1ButtonTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/FrameXML/ActionBarController.lua:308
 PvpRoleStatusTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/FrameXML/PvpPopup.lua:46
 GossipTitleOptionButtonTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/FrameXML/GossipFrame.lua:39
 CommunitiesTicketManagerScrollFrameTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/AddOns/Blizzard_Communities.lua:456
 ButtonFrameTemplateMinimizable = <function> defined @Interface/AddOns/Aurora/Skin/Interface/SharedXML/SharedUIPanelTemplates.lua:612
 MaximizeMinimizeButtonFrameTemplate = <function> defined @Interface/AddOns/Aurora/Skin/Interface/SharedXML/SharedUIPanelT

================================

**Error 2**

Message: ...rora/Skin/Interface/AddOns/Blizzard_AdventureMap.lua:58: attempt to call field 'UIPanelScrollUpButtonTemplate' (a nil value)
Time: Wed Nov  8 14:25:11 2023
Count: 1
Stack: ...rora/Skin/Interface/AddOns/Blizzard_AdventureMap.lua:58: attempt to call field 'UIPanelScrollUpButtonTemplate' (a nil value)
[string "=[C]"]: in function `UIPanelScrollUpButtonTemplate'
[string "@Interface/AddOns/Aurora/Skin/Interface/AddOns/Blizzard_AdventureMap.lua"]:58: in function `addonModule'
[string "@Interface/AddOns/Aurora/Skin/init.lua"]:185: in function <Interface/AddOns/Aurora/Skin/init.lua:149>
[string "=[C]"]: in function `resume'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1195: in function `Login'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1279: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1230>

Locals: (*temporary) = <function> defined =[C]:-1

================================

**Error 3**

Message: .../Skin/Interface/SharedXML/Scroll/OribosScrollBar.lua:16: attempt to call field 'FrameTypeScrollBarButton' (a nil value)
Time: Wed Nov  8 14:25:11 2023
Count: 1
Stack: .../Skin/Interface/SharedXML/Scroll/OribosScrollBar.lua:16: attempt to call field 'FrameTypeScrollBarButton' (a nil value)
[string "=[C]"]: in function `FrameTypeScrollBarButton'
[string "@Interface/AddOns/Aurora/Skin/Interface/SharedXML/Scroll/OribosScrollBar.lua"]:16: in function `OribosScrollBarButtonScripts'
[string "@Interface/AddOns/Aurora/Skin/Interface/SharedXML/Scroll/OribosScrollBar.lua"]:24: in function `OribosScrollBar'
[string "@Interface/AddOns/Aurora/Skin/Interface/AddOns/Blizzard_GarrisonTemplates.lua"]:386: in function `CovenantFollowerListTemplate'
[string "@Interface/AddOns/Aurora/Skin/Interface/AddOns/Blizzard_GarrisonUI.lua"]:848: in function `addonModule'
[string "@Interface/AddOns/Aurora/Skin/init.lua"]:185: in function <Interface/AddOns/Aurora/Skin/init.lua:149>
[string "=[C]"]: in function `resume'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1195: in function `Login'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1279: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1230>

Locals: (*temporary) = <function> defined =[C]:-1

================================

**Error 4**

Message: .../Skin/Interface/SharedXML/Scroll/OribosScrollBar.lua:16: attempt to call field 'FrameTypeScrollBarButton' (a nil value)
Time: Wed Nov  8 14:25:11 2023
Count: 1
Stack: .../Skin/Interface/SharedXML/Scroll/OribosScrollBar.lua:16: attempt to call field 'FrameTypeScrollBarButton' (a nil value)
[string "=[C]"]: in function `FrameTypeScrollBarButton'
[string "@Interface/AddOns/Aurora/Skin/Interface/SharedXML/Scroll/OribosScrollBar.lua"]:16: in function `OribosScrollBarButtonScripts'
[string "@Interface/AddOns/Aurora/Skin/Interface/SharedXML/Scroll/OribosScrollBar.lua"]:24: in function `OribosScrollBar'
[string "@Interface/AddOns/Aurora/Skin/Interface/AddOns/Blizzard_Soulbinds.lua"]:23: in function `ConduitListTemplate'
[string "@Interface/AddOns/Aurora/Skin/Interface/AddOns/Blizzard_Soulbinds.lua"]:107: in function `addonModule'
[string "@Interface/AddOns/Aurora/Skin/init.lua"]:185: in function <Interface/AddOns/Aurora/Skin/init.lua:149>
[string "=[C]"]: in function `resume'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1195: in function `Login'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1279: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1230>

Locals: (*temporary) = <function> defined =[C]:-1

==========================

Thanks a lot !

**Comment by arnvid** [comment]
Try the beta https://github.com/Gethe/Aurora/releases/tag/10.2.0.0.90-beta

**Comment by Heregellas** [comment]
Yeah the latest beta seems to work fine, thanks ! :D
