### ISSUE TITLE
[Bug] Gossip panels font not skinned correctly

### ISSUE THREAD

**Issue by sixtwentysix** [Gethe/Aurora#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

Any NPC with a Gossip panel using the default dark brown Blizzard font color is unskinned by Aurora. All other panels work perfectly, including quest panels. No other addons are installed and I tried a fresh install of Aurora. Please see attached for example.
![aurora_bug](https://github.com/Gethe/Aurora/assets/151413672/36837d52-2ce0-4ca3-af94-b5f42bd6d3d0)

### Steps To Reproduce

Click on any NPC with a Gossip panel. Best example is a city guard.

**Comment by Astrocyde** [comment]
Same issue here; it's been like this ever since 10.2.0 came out.

**Comment by NapalmDawn** [comment]
I get this too even with the new version that just dropped recently.  The addon menu lag has gone away though.
