### ISSUE TITLE
[Bug] Aurora lags addon menu

### ISSUE THREAD

**Issue by zofia1347** [Gethe/Aurora#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

Every time Aurora is activated and I try to access my addon panel from the menu selection it lags my game severely. My game essentially freezes for 5 seconds while attempting to scroll through it. I narrowed it down to Aurora causing the issue and when I turned on lua errors I noticed Aurora errors were popping up every time I tried to scroll.

I pasted some of the errors I was receiving below. I apologize. Not sure how to read any of this so I leave it up to you. Thank you for taking the time to look at this. I love Aurora so much and hope I can use it again!

### Steps To Reproduce

1. Have Aurora addon Enabled
2. Press Esc to open main menu in World of Warcraft
3. Select Addons

### Additional context

`Message: Interface/AddOns/Aurora/Skin/skin.lua:72: attempt to index local 'Button' (a nil value)
Time: Sun Dec  3 09:58:31 2023
Count: 1
Stack: Interface/AddOns/Aurora/Skin/skin.lua:72: attempt to index local 'Button' (a nil value)
[string "@Interface/AddOns/Aurora/Skin/skin.lua"]:72: in function <Interface/AddOns/Aurora/Skin/skin.lua:70>
[string "=[C]"]: in function `FrameTypeButton'
[string "@Interface/AddOns/Aurora/Skin/Interface/SharedXML/ModelSceneTemplates.lua"]:17: in function `ModifyOrbitCameraBaseButtonTemplate'
[string "@Interface/AddOns/Aurora/Skin/Interface/SharedXML/ModelSceneTemplates.lua"]:26: in function `RotateOrbitCameraLeftButtonTemplate'
[string "@Interface/AddOns/Aurora/Skin/Interface/SharedXML/ModelPreviewFrame.lua"]:31: in function `?'
[string "@Interface/AddOns/Aurora/Skin/init.lua"]:165: in function <Interface/AddOns/Aurora/Skin/init.lua:149>

Locals: Button = nil
OnEnter = nil
OnLeave = nil
framesOk = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'Button' (a nil value)"
Hook_Disable = <function> defined @Interface/AddOns/Aurora/Skin/skin.lua:49
Hook_Enable = <function> defined @Interface/AddOns/Aurora/Skin/skin.lua:34
Hook_SetEnabled = <function> defined @Interface/AddOns/Aurora/Skin/skin.lua:63
Base = <table> {
 SetHighlight = <function> defined @Interface/AddOns/Aurora/Skin/deprecated.lua:14
 SetTexture = <function> defined @Interface/AddOns/Aurora/Skin/api.lua:218
 SetFont = <function> defined @Interface/AddOns/Aurora/Skin/api.lua:92
 IsTextureRegistered = <function> defined @Interface/AddOns/Aurora/Skin/api.lua:214
 SetBackdropColor = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:400
 SetBackdrop = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:393
 CropIcon = <function> defined @Interface/AddOns/Aurora/Skin/api.lua:80
 GetAddonSkins = <function> defined @Interface/AddOns/Aurora/Skin/api.lua:57
 AddSkin = <function> defined @Interface/AddOns/Aurora/Skin/api.lua:41
 CreateBackdrop = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:374
 RegisterTexture = <function> defined @Interface/AddOns/Aurora/Skin/api.lua:228
}
Color = <table> {
 highlight = <table> {
 }
 cyan = <table> {
 }
 Lightness = <function> defined @Interface/AddOns/Aurora/Skin/color.lua:190
 grayLight = <table> {
 }
 ruby = <table> {
 }
 Saturation = <function> defined @Interface/AddOns/Aurora/Skin/color.lua:169
 button = <table> {
 }
 orange = <table> {
 }
 red = <table> {
 }
 Hue = <function> defined @Interface/AddOns/Aurora/Skin/color.lua:141
 magenta = <table> {
 }
 blue = <table> {
 }
 frame = <table> {
 }
 white = <table> {
 }
 Create = <function> defined @Interface/AddOns/Aurora/Skin/color.lua:111
 jade = <table> {
 }
 grayDark = <table> {
 }
 violet = <table> {
 }
 black = <table> {
 }
 green = <table> {
 }
 lime = <table> {
 }
 yellow = <table> {
 }
 marine = <table> {
 }
 gray = <table> {
 }
}
MinimalOnEnter = <function> defined @Interface/AddOns/Aurora/Skin/skin.lua:26
MinimalOnLeave = <function> defined @Interface/AddOns/Aurora/Skin/skin.lua:29
DISABLED_COLOR = <table> {
 a = 1
 colorStr = "ff2d2d2d"
 b = 0.176471
 Lightness = <function> defined @Interface/AddOns/Aurora/Skin/color.lua:76
 g = 0.176471
 GetRGBA = <function> defined @Interface/SharedXML/Color.lua:29
 Saturation = <function> defined @Interface/AddOns/Aurora/Skin/color.lua:70
 SetRGB = <function> defined @Interface/SharedXML/Color.lua:44
 Hue = <function> defined @Interface/AddOns/Aurora/Skin/color.lua:64
 GetRGB = <function> defined @Interface/SharedXML/Color.lua:21
 r = 0.176471
 GenerateHexColorMarkup = <function> defined @Interface/SharedXML/Color.lua:52
 WrapTextInColorCode = <function> defined @Interface/SharedXML/Color.lua:56
 GenerateHexColor = <function> defined @Interface/AddOns/Aurora/Skin/color.lua:39
 IsEqualTo = <function> defined @Interface/AddOns/Aurora/Skin/color.lua:47
 isAchromatic = true
 SetRGBA = <functio`

`Message: ...AddOns/Aurora/Skin/Interface/SharedXML/AddonList.lua:14: attempt to concatenate a nil value
Time: Sun Dec  3 10:00:26 2023
Count: 19
Stack: ...AddOns/Aurora/Skin/Interface/SharedXML/AddonList.lua:14: attempt to concatenate a nil value
[string "@Interface/AddOns/Aurora/Skin/Interface/SharedXML/AddonList.lua"]:14: in function `TriStateCheckbox_SetState'
[string "@Interface/AddOns/Aurora/Skin/Interface/SharedXML/AddonList.lua"]:32: in function <...AddOns/Aurora/Skin/Interface/SharedXML/AddonList.lua:31>
[string "=[C]"]: in function `AddonList_InitButton'
[string "@Interface/SharedXML/AddonList.lua"]:231: in function `initializer'
[string "@Interface/SharedXML/Scroll/ScrollBoxListView.lua"]:382: in function `InvokeInitializer'
[string "@Interface/SharedXML/Scroll/ScrollBoxListView.lua"]:391: in function `InvokeInitializers'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:718: in function `Update'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:258: in function `SetScrollPercentageInternal'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:250: in function `SetScrollPercentage'
[string "@Interface/SharedXML/Scroll/ScrollController.lua"]:98: in function `ScrollInDirection'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:232: in function `ScrollInDirection'
[string "@Interface/SharedXML/Scroll/ScrollController.lua"]:89: in function <Interface/SharedXML/Scroll/ScrollController.lua:87>

Locals: checked = 2
checkButton = CheckButton {
 0 = <userdata>
 _returnColor = <table> {
 }
 CheckedTexture = Texture {
 }
 GetBackdropColor = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:285
 SetBackdropOptions = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:364
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 GetBackdropTexture = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:333
 UnlockHighlight = <function> defined =[C]:-1
 ApplyBackdrop = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:193
 SetBackdrop = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:246
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 state = 2
 GetBackdropBorderColor = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:305
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 LockHighlight = <function> defined =[C]:-1
 SetBackdropGradient = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:311
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 SetBackdropOption = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:342
 SetBackdropLayer = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:319
 backdropInfo = <table> {
 }
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 GetBackdropOption = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:358
 BottomEdge = Texture {
 }
 _onEnter = <function> defined @Interface/AddOns/Aurora/Skin/api.lua:182
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 Center = Texture {
 }
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 TopEdge = Texture {
 }
 _backdropInfo = <table> {
 }
 _onLeave = <function> defined @Interface/AddOns/Aurora/Skin/api.lua:185
 OnBackdropLoaded = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:175
 BottomRightCorner = Texture {
 }
 GetBackdropLayer = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:328
 BottomLeftCorner = Texture {
 }
 TopRightCorner = Texture {
 }
 SetupPieceVisuals = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:178
 SetBackdropColor = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:275
 LeftEdge = Texture {
 }
 SetBackdropBorderColor = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:289
}
(*temporary) = <table> {
 ERR_OUT_OF_CHI `
 
 `Message: ...AddOns/Aurora/Skin/Interface/SharedXML/AddonList.lua:14: attempt to concatenate a nil value
Time: Sun Dec  3 10:00:26 2023
Count: 19
Stack: ...AddOns/Aurora/Skin/Interface/SharedXML/AddonList.lua:14: attempt to concatenate a nil value
[string "@Interface/AddOns/Aurora/Skin/Interface/SharedXML/AddonList.lua"]:14: in function `TriStateCheckbox_SetState'
[string "@Interface/AddOns/Aurora/Skin/Interface/SharedXML/AddonList.lua"]:32: in function <...AddOns/Aurora/Skin/Interface/SharedXML/AddonList.lua:31>
[string "=[C]"]: in function `AddonList_InitButton'
[string "@Interface/SharedXML/AddonList.lua"]:231: in function `initializer'
[string "@Interface/SharedXML/Scroll/ScrollBoxListView.lua"]:382: in function `InvokeInitializer'
[string "@Interface/SharedXML/Scroll/ScrollBoxListView.lua"]:391: in function `InvokeInitializers'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:718: in function `Update'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:258: in function `SetScrollPercentageInternal'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:250: in function `SetScrollPercentage'
[string "@Interface/SharedXML/Scroll/ScrollController.lua"]:98: in function `ScrollInDirection'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:232: in function `ScrollInDirection'
[string "@Interface/SharedXML/Scroll/ScrollController.lua"]:89: in function <Interface/SharedXML/Scroll/ScrollController.lua:87>

Locals: checked = 2
checkButton = CheckButton {
 0 = <userdata>
 _returnColor = <table> {
 }
 CheckedTexture = Texture {
 }
 GetBackdropColor = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:285
 SetBackdropOptions = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:364
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 GetBackdropTexture = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:333
 UnlockHighlight = <function> defined =[C]:-1
 ApplyBackdrop = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:193
 SetBackdrop = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:246
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 state = 2
 GetBackdropBorderColor = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:305
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 LockHighlight = <function> defined =[C]:-1
 SetBackdropGradient = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:311
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 SetBackdropOption = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:342
 SetBackdropLayer = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:319
 backdropInfo = <table> {
 }
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 GetBackdropOption = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:358
 BottomEdge = Texture {
 }
 _onEnter = <function> defined @Interface/AddOns/Aurora/Skin/api.lua:182
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 Center = Texture {
 }
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 TopEdge = Texture {
 }
 _backdropInfo = <table> {
 }
 _onLeave = <function> defined @Interface/AddOns/Aurora/Skin/api.lua:185
 OnBackdropLoaded = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:175
 BottomRightCorner = Texture {
 }
 GetBackdropLayer = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:328
 BottomLeftCorner = Texture {
 }
 TopRightCorner = Texture {
 }
 SetupPieceVisuals = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:178
 SetBackdropColor = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:275
 LeftEdge = Texture {
 }
 SetBackdropBorderColor = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:289
}
(*temporary) = <table> {
 ERR_OUT_OF_CHI `

**Comment by zofia1347** [comment]
![image](https://github.com/Gethe/Aurora/assets/73046345/472200d5-7ecd-4e1c-a49a-452fe3e4d636)

Also - I apologize if some of the errors aren't complete. I couldn't select "next" on the lua errors to copy and paste some further errors I was experiencing as exampled in the picture.

**Comment by NapalmDawn** [comment]
This has stopped for me in the newest version on wowinterface.

**Comment by zofia1347** [comment]
Yes, the latest update pushed out has fixed this. Thank you :)
