### ISSUE TITLE
[Bug] Doesn't seem to work + wow client labels the addon as outdated.

### ISSUE THREAD

**Issue by Pixelatex** [Gethe/Aurora#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Classic Era

### Current Behavior

I installed aurora through curseforge and wow gave me warnings about the addon being outdated, I loaded it anyway and while it doesn't give any lua errors... it also doesn't do a thing. The menu and settings and such do function but visually, none of the game's UI is modified.

### Expected Behavior

It should work?

### Steps To Reproduce

Install aurora via curseforge
Run the latest version of wow classic (SOD in my case if this matters)
See nothing because the addon doesn't work sadly.

### Additional context

Given that wow is complaining about the addon being outdated.., I assume it's behind on the latest changes?

**Comment by arnvid** [comment]
@Pixelatex - I have not updated anything for non-Retail versions.. Possibly It should still work if it uses similar or same api as retail. I do not play Classic myself so have not had any possibility to check it.. Should be just a quick TOC change tho.

**Comment by Pixelatex** [comment]
Can I ... do something to fix it and make a pr for you? Have 0 experience with creating wow addons but am experience as a developer

**Comment by Pixelatex** [comment]
> @Pixelatex - I have not updated anything for non-Retail versions.. Possibly It should still work if it uses similar or same api as retail. I do not play Classic myself so have not had any possibility to check it.. Should be just a quick TOC change tho.

So I have updated the TOC to v1.15 and that did fix the out of date issue but nothing seems to visually change at all.
I will take a look tonight if I can figure out what's wrong with it

**Comment by Master0fEvil** [comment]
> > @Pixelatex - I have not updated anything for non-Retail versions.. Possibly It should still work if it uses similar or same api as retail. I do not play Classic myself so have not had any possibility to check it.. Should be just a quick TOC change tho.
> 
> So I have updated the TOC to v1.15 and that did fix the out of date issue but nothing seems to visually change at all. I will take a look tonight if I can figure out what's wrong with it

how's it going? any luck getting it to work with classic?

**Comment by arnvid** [comment]
Closing this for now - am working on redoing the Classic/SOD/etc implementation. But for now I have disabled the packaging of these modules and closing the tickets related to this. Sorry I cannot update anymore at this time.  The wow-ui-sources are getting more in-line to make this a reality and thus why I am working on a restructure of all of these things.
