### ISSUE TITLE
[Bug] Is addon working for people? 

### ISSUE THREAD

**Issue by Criddy** [Gethe/Aurora#11]
Since the newest retail update the addon has seem to not been working. I had saw my previous bug report was closed so I was curious to see if there was a fix released or maybe the addon was just going to not be updated anymore? Was unsure and hoping to find clarity. Hope it gets worked out soon this was my favorite addon by far.

**Comment by arnvid** [comment]
@Criddy - this one should be fairly stable now.. a few minor things here and there.

**Comment by Criddy** [comment]
@arnvid Was there an update? I'm not seeing one on curse app atm.

**Comment by arnvid** [comment]
@Criddy - no, not yet on Curseforge etc since development is still happening. 9.1.5 did a bit of mess around on certain parts.
But it is in the git repos that we use.

**Comment by Criddy** [comment]
@arnvid ahh gotcha! Not quite sure how to update addon that way or use the git repos so I'll probably just wait for the curse update! But am def glad to know things are starting to be fixed! This was def one off my fav addons to use just made everything so much cleaner looking!
