### ISSUE TITLE
[Bug] Quest text too dark

### ISSUE THREAD

**Issue by zofia1347** [Gethe/Aurora#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

With all addons disabled except for Aurora, all the quest texts are now too dark to read. Other menus seem to be readable though. Is this something Aurora can mess with to help or no? Thank you so much for your time/looking into this!

![image](https://github.com/Gethe/Aurora/assets/73046345/a5856f40-f454-4353-bfa2-10135c40903f)

**Comment by NapalmDawn** [comment]
I've had this too for some time.  A recent Aurora update fixed the lag when scrolling through the addons list but the quest text issue is still happening for me. I either have to turn it off or like turn my camera so that certain colors are behind the quest text.

**Comment by Linktotherescue** [comment]
Go into your blizzard settings and change quest text contrasst to dark. 

It will fix your issue for you.

**Comment by Astrocyde** [comment]
> Go into your blizzard settings and change quest text contrasst to dark.
> 
> It will fix your issue for you.

where exactly do you mean "blizzard settings"? i can't find any option related to quest text contrast

**Comment by zofia1347** [comment]
> > Go into your blizzard settings and change quest text contrasst to dark.
> > It will fix your issue for you.
> 
> where exactly do you mean "blizzard settings"? i can't find any option related to quest text contrast

@Astrocyde Open your options and under Accessibility -> General there will be a Quest Text Contrast option. Just select the "dark" option and it should be fixed.

Thank you @Linktotherescue so much for your help! I can't believe it was a quick fix under the options like this! Appreciate you.
