### ISSUE TITLE
[Bug] LFG isn't skinned (as some others) and doesn't show roles (tank/healer/DPS) anymore

### ISSUE THREAD

**Issue by Heregellas** [Gethe/Aurora#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail 10.2.5

### Current Behavior

The frame isn't skinned & the roles are not showing, as you can see on this screenshot :

https://i.gyazo.com/cdb4b761e52bc9537cb257252c63b092.png

(Which makes it super confusing when tagging in a group :p)

Some other frames are not skinned properly neither (the Auction House, or the Mailbox, for instance).

### Additional context

An additional note : this behavior seems to happen after each and every patch (I know they change LUA & stuff, but since it's a bit weird I wanted to write it, since you'll probably see tickets being open with this same bug on a regular basis before the fix is available)

Thanks a lot in advance for a fix <3

**Comment by arnvid** [comment]
Thanks for reporting this. I did not notice this while going through the load errors - but will check tonight

**Comment by Heregellas** [comment]
Hey,

It seems the update from yesterday (10.2.5.0) fixed this (I just checked that minutes ago, since I didn't have any notification at first for the issue), so it seems all good for now, and I'll close the issue.

Thanks in any case ! <3 Sorry for the slightly delayed update.

Have a nice day !
