### ISSUE TITLE
[Bug]ActionBArController.lua:575 attampt to index field 'Background' (a nil value)

### ISSUE THREAD

**Issue by EkaterinaR** [Gethe/Aurora#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

Hi,
On Retail, 10.2.5 (53007) I get the below error with only Aurora, BugGrabber and Bugsack installed, then 
`3x ...rora/Skin/FrameXML/ActionBarController.lua:575: attempt to index field 'Background' (a nil value)
[string "@Aurora/Skin/FrameXML/ActionBarController.lua"]:575: in function `?'
[string "@Aurora/Skin/init.lua"]:165: in function <Aurora/Skin/init.lua:149>

Locals:
MainMenuBar = MainMenuBar {
 0 = <userdata>
 QuickKeybindRightShadow = Texture {
 }
 GetShowAllButtons = <function> defined @FrameXML/ActionBar.lua:179
 UpdateSystemSettingAlwaysShowButtons = <function> defined @FrameXML/EditModeSystemTemplates.lua:994
 UpdateMagnetismRegistration = <function> defined @FrameXML/EditModeSystemTemplates.lua:731
 GetSnapOffsets = <function> defined @FrameXML/EditModeSystemTemplates.lua:609
 UpdateFrameStrata = <function> defined @FrameXML/ActionBar.lua:183
 IsFrameAnchoredToMe = <function> defined @FrameXML/EditModeSystemTemplates.lua:694
 TrySetCompositeNumberSettingValue = <function> defined @FrameXML/EditModeSystemTemplates.lua:212
 downKeys = <table> {
 }
 GetFixedSize = <function> defined @SharedXML/LayoutFrame.lua:156
 buttonTemplate = "MainBarActionBarButtonTemplate"
 GetFixedWidth = <function> defined @SharedXML/LayoutFrame.lua:148
 useDefaultAnchors = false
 GetSelectionOffset = <function> defined @FrameXML/EditModeSystemTemplates.lua:540
 ResetToDefaultPosition = <function> defined @FrameXML/EditModeSystemTemplates.lua:254
 oldGridSettings = <table> {
 }
 GetScaledSelectionSides = <function> defined @FrameXML/EditModeSystemTemplates.lua:532
 SelectSystem = <function> defined @FrameXML/EditModeSystemTemplates.lua:763
 SetFixedWidth = <function> defined @SharedXML/LayoutFrame.lua:135
 GetFrameMagneticEligibility = <function> defined @FrameXML/EditModeSystemTemplates.lua:714
 AddLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:55
 IsBelowFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:499
 UpdateSystemSettingIconSize = <function> defined @FrameXML/EditModeSystemTemplates.lua:933
 SetFixedSize = <function> defined @SharedXML/LayoutFrame.lua:143
 HasActiveChanges = <function> defined @FrameXML/EditModeSystemTemplates.lua:381
 GetScaledCenter = <function> defined @FrameXML/EditModeSystemTemplates.lua:525
 DoesSettingDisplayValueEqual = <function> defined @FrameXML/EditModeSystemTemplates.lua:445
 OnLoad = <function> defined @FrameXML/MainMenuBar.lua:6
 UpdateDisplayInfoOptions = <function> defined @FrameXML/EditModeSystemTemplates.lua:456
 ActionBarPageNumber = Frame {
 }
 GetSystemName = <function> defined @FrameXML/EditModeSystemTemplates.lua:822
 ProcessMovementKey = <function> defined @FrameXML/EditModeSystemTemplates.lua:39
 GetSettingValueBool = <function> defined @FrameXML/EditModeSystemTemplates.lua:436
 HasCompositeNumberSetting = <function> defined @FrameXML/EditModeSystemTemplates.lua:385
 IsLayoutFrame = <function> defined @SharedXML/LayoutFrame.lua:36
 DoesSettingValueEqual = <function> defined @FrameXML/EditModeSystemTemplates.lua:440
 MarkDirty = <function> defined @SharedXML/LayoutFrame.lua:99
 ShouldResetSettingsDialogAnchors = <function> defined @FrameXML/EditModeSystemTemplates.lua:168
 UpdateGridLayout = <function> defined @FrameXML/EditModeSystemTemplates.lua:870
 IsToTheLeftOfFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:481
 GetSettingsDialogAnchor = <function> defined @FrameXML/EditModeSystemTemplates.lua:465
 OnSystemLoad = <function> defined @FrameXML/EditModeSystemTemplates.lua:3
 ClearFrameSnap = <function> defined @FrameXML/EditModeSystemTemplates.lua:653
 GetCombinedCenterOffset = <function> defined @FrameXML/EditModeSystemTemplates.lua:596
 SetupSettingsDialogAnchor = <function> defined @FrameXML/EditModeSystemTemplates.lua:369
 IsShownOverride = <function> defined @FrameXML/ActionBar.lua:282
 dirty = false
 SetPointBase = <function> defined =[C]:-1
 UpdateSystem = <function> defined @FrameXML/EditModeSystemTemplates.lua:833
 CacheGridSettings = <function> defined @FrameXML/ActionBar.lua:65
 Up`

### Steps To Reproduce

1. Install Aurora. 2. Load into game.

**Comment by arnvid** [comment]
Please try latest version

**Comment by EkaterinaR** [comment]
Hi, With 10.2.5.1 and only Aurora and Bugsack and Bugrabber  enabled.

9x ...rora/Skin/FrameXML/ActionBarController.lua:575: attempt to index field 'Background' (a nil value)
[string "@Aurora/Skin/FrameXML/ActionBarController.lua"]:575: in function `?'
[string "@Aurora/Skin/init.lua"]:165: in function <Aurora/Skin/init.lua:149>

Locals:
MainMenuBar = MainMenuBar {
 0 = <userdata>
 QuickKeybindRightShadow = Texture {
 }
 GetShowAllButtons = <function> defined @FrameXML/ActionBar.lua:179
 UpdateSystemSettingAlwaysShowButtons = <function> defined @FrameXML/EditModeSystemTemplates.lua:994
 UpdateMagnetismRegistration = <function> defined @FrameXML/EditModeSystemTemplates.lua:731
 GetSnapOffsets = <function> defined @FrameXML/EditModeSystemTemplates.lua:609
 UpdateFrameStrata = <function> defined @FrameXML/ActionBar.lua:183
 IsFrameAnchoredToMe = <function> defined @FrameXML/EditModeSystemTemplates.lua:694
 TrySetCompositeNumberSettingValue = <function> defined @FrameXML/EditModeSystemTemplates.lua:212
 downKeys = <table> {
 }
 GetFixedSize = <function> defined @SharedXML/LayoutFrame.lua:156
 buttonTemplate = "MainBarActionBarButtonTemplate"
 GetFixedWidth = <function> defined @SharedXML/LayoutFrame.lua:148
 useDefaultAnchors = false
 GetSelectionOffset = <function> defined @FrameXML/EditModeSystemTemplates.lua:540
 ResetToDefaultPosition = <function> defined @FrameXML/EditModeSystemTemplates.lua:254
 oldGridSettings = <table> {
 }
 GetScaledSelectionSides = <function> defined @FrameXML/EditModeSystemTemplates.lua:532
 SelectSystem = <function> defined @FrameXML/EditModeSystemTemplates.lua:763
 SetFixedWidth = <function> defined @SharedXML/LayoutFrame.lua:135
 GetFrameMagneticEligibility = <function> defined @FrameXML/EditModeSystemTemplates.lua:714
 AddLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:55
 IsBelowFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:499
 UpdateSystemSettingIconSize = <function> defined @FrameXML/EditModeSystemTemplates.lua:933
 SetFixedSize = <function> defined @SharedXML/LayoutFrame.lua:143
 HasActiveChanges = <function> defined @FrameXML/EditModeSystemTemplates.lua:381
 GetScaledCenter = <function> defined @FrameXML/EditModeSystemTemplates.lua:525
 DoesSettingDisplayValueEqual = <function> defined @FrameXML/EditModeSystemTemplates.lua:445
 OnLoad = <function> defined @FrameXML/MainMenuBar.lua:6
 UpdateDisplayInfoOptions = <function> defined @FrameXML/EditModeSystemTemplates.lua:456
 ActionBarPageNumber = Frame {
 }
 GetSystemName = <function> defined @FrameXML/EditModeSystemTemplates.lua:822
 ProcessMovementKey = <function> defined @FrameXML/EditModeSystemTemplates.lua:39
 GetSettingValueBool = <function> defined @FrameXML/EditModeSystemTemplates.lua:436
 HasCompositeNumberSetting = <function> defined @FrameXML/EditModeSystemTemplates.lua:385
 IsLayoutFrame = <function> defined @SharedXML/LayoutFrame.lua:36
 DoesSettingValueEqual = <function> defined @FrameXML/EditModeSystemTemplates.lua:440
 MarkDirty = <function> defined @SharedXML/LayoutFrame.lua:99
 ShouldResetSettingsDialogAnchors = <function> defined @FrameXML/EditModeSystemTemplates.lua:168
 UpdateGridLayout = <function> defined @FrameXML/EditModeSystemTemplates.lua:870
 IsToTheLeftOfFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:481
 GetSettingsDialogAnchor = <function> defined @FrameXML/EditModeSystemTemplates.lua:465
 OnSystemLoad = <function> defined @FrameXML/EditModeSystemTemplates.lua:3
 ClearFrameSnap = <function> defined @FrameXML/EditModeSystemTemplates.lua:653
 GetCombinedCenterOffset = <function> defined @FrameXML/EditModeSystemTemplates.lua:596
 SetupSettingsDialogAnchor = <function> defined @FrameXML/EditModeSystemTemplates.lua:369
 IsShownOverride = <function> defined @FrameXML/ActionBar.lua:282
 dirty = false
 SetPointBase = <function> defined =[C]:-1
 UpdateSystem = <function> defined @FrameXML/EditModeSystemTemplates.lua:833
 CacheGridSettings = <function> defined @FrameXML/ActionBar.lua:65
 Up

**Comment by arnvid** [comment]
Do you get this with latest version 10.2.7.1

**Comment by alazare619** [comment]
This is still occuring with latest. Unchecking the main menu bar in the options seems to fix it to where it doesnt show up. But also the default bag ui (one bag version) is not skinned

**Comment by arnvid** [comment]
Should be gone with 10.2.7.2
