### ISSUE TITLE
[Qustion] NPC Text is too Dark to read it

### ISSUE THREAD

**Issue by Fm4x** [Gethe/Aurora#114]
![image](https://github.com/Gethe/Aurora/assets/161977808/6b1ee338-aaac-4b9b-b045-a8e1b0c23f62)

Hey Guys, i really enjoying the Addon, but for any Reason the Font of NPC Windows is really Dark and hard to read. Any Ideas?

**Comment by arnvid** [comment]
@Fm4x 
What I did in RealUI was to add:
    if not (tonumber(_G.GetCVar("questTextContrast")) == 4) then
        _G.SetCVar("questTextContrast", 4);
    end

![image](https://github.com/Gethe/Aurora/assets/876871/ece029f2-0d49-4492-9bc6-47d827edd531)
