### ISSUE TITLE
[Bug] Lots of Errors on SoD/Classic

### ISSUE THREAD

**Issue by cdmichaelb** [Gethe/Aurora#115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Classic SoD

### Current Behavior

Doesn't work at all. Lots of errors.

### Expected Behavior

Work. No errors.

### Steps To Reproduce

Install addon.

### Additional context

`3x Interface\FrameXML\FrameXML_Vanilla.toc:1 Aurora/Aurora.toc:18 Couldn't open Aurora/SkinAddOns_Vanilla.xml`

`3x Interface\FrameXML\FrameXML_Vanilla.toc:1 Aurora/Aurora.toc:17 Couldn't open Aurora/Skin/FrameXML/FrameXML_Vanilla.xml`

`3x Aurora/Aurora.toc:18 Couldn't open Aurora/SkinAddOns_Vanilla.xml`

`3x Aurora/Aurora.toc:17 Couldn't open Aurora/Skin/FrameXML/FrameXML_Vanilla.xml`

```
3x Aurora/aurora.lua:152: hooksecurefunc(): FriendsFrame is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Aurora/aurora.lua"]:152: in function `OnLoad'
[string "@Aurora/Skin/init.lua"]:155: in function <Aurora/Skin/init.lua:149>

Locals:
```

Based on the errors, my assumption is either that it doesn't work on classic, or there's an incompatibility with another addon? I found it in the classic section on addons though.

**Comment by arnvid** [comment]
@cdmichaelb - I dont play classic or wotlk wow myself.- But I just loaded in the game with Aurora only loaded. 
I dont see any errors, but I also dont see what I would have expected to see. I am debating if to remove all the non retail code.
Or to spend time on fixing it.  I maintain it mainly as part of one the core dependencies of RealUI

**Comment by cdmichaelb** [comment]
I actually quit myself, so I don't have a horse in the race anymore lol. Your addon did look nice though.

**Comment by asijdaushd** [comment]
> @cdmichaelb - I dont play classic or wotlk wow myself.- But I just loaded in the game with Aurora only loaded.
> 
> > I dont see any errors, but I also dont see what I would have expected to see
> > Ok.. installing BugGrabber actually showed the errors.. looking now..
> 
> I am debating if to remove all the non retail code. Or to spend time on fixing it. I maintain it mainly as part of one the core dependencies of RealUI

plz update if u can, aurora seems to be one of a kind addon(atleast thats standalone)

**Comment by arnvid** [comment]
Closing this for now - am working on redoing the Classic/SOD/etc implementation. But for now I have disabled the packaging of these modules and closing the tickets related to this. Sorry I cannot update anymore at this time.  The wow-ui-sources are getting more in-line to make this a reality and thus why I am working on a restructure of all of these things.
