### ISSUE TITLE
[Bug] Not working at all since 10.2.7 (Retail)

### ISSUE THREAD

**Issue by Heregellas** [Gethe/Aurora#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail 10.2.7

### Current Behavior

Hey,

The add-on is not working at all since the patch today.
Here are the errors for troubleshooting : 

Message: Interface/AddOns/Aurora/gui.lua:201: attempt to call field 'BlizzardOptionsPanel_Slider_Enable' (a nil value)
Time: Wed May  8 11:57:27 2024
Count: 1
Stack: Interface/AddOns/Aurora/gui.lua:201: attempt to call field 'BlizzardOptionsPanel_Slider_Enable' (a nil value)
[string "@Interface/AddOns/Aurora/gui.lua"]:201: in function `createSlider'
[string "@Interface/AddOns/Aurora/gui.lua"]:298: in main chunk

Locals: parent = AuroraOptions {
 0 = <userdata>
 name = "Aurora"
}
value = "alpha"
text = "Backdrop opacity *"
slider = AuroraOptionsSlider1 {
 0 = <userdata>
 NineSlice = Frame {
 }
 Thumb = AuroraOptionsSlider1Thumb {
 }
 value = "alpha"
 Text = AuroraOptionsSlider1Text {
 }
 High = AuroraOptionsSlider1High {
 }
 Low = AuroraOptionsSlider1Low {
 }
}
(*temporary) = nil
(*temporary) = AuroraOptionsSlider1 {
 0 = <userdata>
 NineSlice = Frame {
 }
 Thumb = AuroraOptionsSlider1Thumb {
 }
 value = "alpha"
 Text = AuroraOptionsSlider1Text {
 }
 High = AuroraOptionsSlider1High {
 }
 Low = AuroraOptionsSlider1Low {
 }
}
(*temporary) = "attempt to call field 'BlizzardOptionsPanel_Slider_Enable' (a nil value)"
numSliders = 1
private = <table> {
 isPatch = false
 disabled = <table> {
 }
 uiScale = 1
 API_MINOR = 8
 OnLoad = <function> defined @Interface/AddOns/Aurora/aurora.lua:40
 isBCC = true
 updateHighlightColor = <function> defined @Interface/AddOns/Aurora/Skin/color.lua:434
 wago = <table> {
 }
 AZERITE_COLORS = <table> {
 }
 backdrop = <table> {
 }
 isClassic = true
 classColorsReset = <function> defined @Interface/AddOns/Aurora/Skin/color.lua:405
 setColorCache = <function> defined @Interface/AddOns/Aurora/Skin/color.lua:398
 COVENANT_COLORS = <table> {
 }
 Aurora = <table> {
 }
 textures = <table> {
 }
 API_MAJOR = 0
 nop = <function> defined @Interface/AddOns/Aurora/Skin/init.lua:90
 charClass = <table> {
 }
 isVanilla = false
 isRetail = false
 isWrath = false
 FrameXML = <table> {
 }
 AddOns = <table> {
 }
 UpdateUIScale = <function> defined @Interface/AddOns/Aurora/Skin/init.lua:40
 fileOrder = <table> {
 }
 FACTION_COLORS = <table> {
 }
 debug = <function> defined @Interface/AddOns/Aurora/Skin/init.lua:90
 SharedXML = <table> {
 }
 shouldSkip = <function> defined @Interface/AddOns/Aurora/Skin/init.lua:22
 font = <table> {
 }
}
OnValueChanged = <function> defined @Interface/AddOns/Aurora/gui.lua:181

==== And the 2nd error =====

Message: Interface/AddOns/Aurora/gui.lua:201: attempt to call field 'BlizzardOptionsPanel_Slider_Enable' (a nil value)
Time: Wed May  8 11:57:27 2024
Count: 1
Stack: Interface/AddOns/Aurora/gui.lua:201: attempt to call field 'BlizzardOptionsPanel_Slider_Enable' (a nil value)
[string "@Interface/AddOns/Aurora/gui.lua"]:201: in function `createSlider'
[string "@Interface/AddOns/Aurora/gui.lua"]:298: in main chunk

Locals: parent = AuroraOptions {
 0 = <userdata>
 name = "Aurora"
}
value = "alpha"
text = "Backdrop opacity *"
slider = AuroraOptionsSlider1 {
 0 = <userdata>
 NineSlice = Frame {
 }
 Thumb = AuroraOptionsSlider1Thumb {
 }
 value = "alpha"
 Text = AuroraOptionsSlider1Text {
 }
 High = AuroraOptionsSlider1High {
 }
 Low = AuroraOptionsSlider1Low {
 }
}
(*temporary) = nil
(*temporary) = AuroraOptionsSlider1 {
 0 = <userdata>
 NineSlice = Frame {
 }
 Thumb = AuroraOptionsSlider1Thumb {
 }
 value = "alpha"
 Text = AuroraOptionsSlider1Text {
 }
 High = AuroraOptionsSlider1High {
 }
 Low = AuroraOptionsSlider1Low {
 }
}
(*temporary) = "attempt to call field 'BlizzardOptionsPanel_Slider_Enable' (a nil value)"
numSliders = 1
private = <table> {
 isPatch = false
 disabled = <table> {
 }
 uiScale = 1
 API_MINOR = 8
 OnLoad = <function> defined @Interface/AddOns/Aurora/aurora.lua:40
 isBCC = true
 updateHighlightColor = <function> defined @Interface/AddOns/Aurora/Skin/color.lua:434
 wago = <table> {
 }
 AZERITE_COLORS = <table> {
 }
 backdrop = <table> {
 }
 isClassic = true
 classColorsReset = <function> defined @Interface/AddOns/Aurora/Skin/color.lua:405
 setColorCache = <function> defined @Interface/AddOns/Aurora/Skin/color.lua:398
 COVENANT_COLORS = <table> {
 }
 Aurora = <table> {
 }
 textures = <table> {
 }
 API_MAJOR = 0
 nop = <function> defined @Interface/AddOns/Aurora/Skin/init.lua:90
 charClass = <table> {
 }
 isVanilla = false
 isRetail = false
 isWrath = false
 FrameXML = <table> {
 }
 AddOns = <table> {
 }
 UpdateUIScale = <function> defined @Interface/AddOns/Aurora/Skin/init.lua:40
 fileOrder = <table> {
 }
 FACTION_COLORS = <table> {
 }
 debug = <function> defined @Interface/AddOns/Aurora/Skin/init.lua:90
 SharedXML = <table> {
 }
 shouldSkip = <function> defined @Interface/AddOns/Aurora/Skin/init.lua:22
 font = <table> {
 }
}
OnValueChanged = <function> defined @Interface/AddOns/Aurora/gui.lua:181

Thank you in advance, and have a nice day !

**Comment by Heregellas** [comment]
Other errors I got (tested both beta & alpha new versions, both are not working unfortunately) : 


=== Error 1 ===

Message: Interface/AddOns/Aurora/aurora.lua:152: hooksecurefunc(): FriendsFrame is not a function
Time: Fri May 10 23:52:00 2024
Count: 1
Stack: Interface/AddOns/Aurora/aurora.lua:152: hooksecurefunc(): FriendsFrame is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface/AddOns/Aurora/aurora.lua"]:152: in function `OnLoad'
[string "@Interface/AddOns/Aurora/Skin/init.lua"]:155: in function <Interface/AddOns/Aurora/Skin/init.lua:149>

Locals;



=== Error 2 ===

Message: ...rora/Skin/Interface/AddOns/Blizzard_AdventureMap.lua:58: attempt to call field 'UIPanelScrollUpButtonTemplate' (a nil value)
Time: Fri May 10 23:52:07 2024
Count: 1
Stack: ...rora/Skin/Interface/AddOns/Blizzard_AdventureMap.lua:58: attempt to call field 'UIPanelScrollUpButtonTemplate' (a nil value)
[string "=[C]"]: in function `UIPanelScrollUpButtonTemplate'
[string "@Interface/AddOns/Aurora/Skin/Interface/AddOns/Blizzard_AdventureMap.lua"]:58: in function `addonModule'
[string "@Interface/AddOns/Aurora/Skin/init.lua"]:185: in function <Interface/AddOns/Aurora/Skin/init.lua:149>
[string "=[C]"]: in function `resume'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1286: in function `Login'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1373: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1321>

Locals: (*temporary) = <function> defined =[C]:-1


=== Error 3 ===

Message: .../Skin/Interface/SharedXML/Scroll/OribosScrollBar.lua:16: attempt to call field 'FrameTypeScrollBarButton' (a nil value)
Time: Fri May 10 23:52:07 2024
Count: 1
Stack: .../Skin/Interface/SharedXML/Scroll/OribosScrollBar.lua:16: attempt to call field 'FrameTypeScrollBarButton' (a nil value)
[string "=[C]"]: in function `FrameTypeScrollBarButton'
[string "@Interface/AddOns/Aurora/Skin/Interface/SharedXML/Scroll/OribosScrollBar.lua"]:16: in function `OribosScrollBarButtonScripts'
[string "@Interface/AddOns/Aurora/Skin/Interface/SharedXML/Scroll/OribosScrollBar.lua"]:24: in function `OribosScrollBar'
[string "@Interface/AddOns/Aurora/Skin/Interface/AddOns/Blizzard_GarrisonTemplates.lua"]:386: in function `CovenantFollowerListTemplate'
[string "@Interface/AddOns/Aurora/Skin/Interface/AddOns/Blizzard_GarrisonUI.lua"]:848: in function `addonModule'
[string "@Interface/AddOns/Aurora/Skin/init.lua"]:185: in function <Interface/AddOns/Aurora/Skin/init.lua:149>
[string "=[C]"]: in function `resume'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1286: in function `Login'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1373: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1321>

Locals: (*temporary) = <function> defined =[C]:-1


=== Error 4 ===

Message: .../Skin/Interface/SharedXML/Scroll/OribosScrollBar.lua:16: attempt to call field 'FrameTypeScrollBarButton' (a nil value)
Time: Fri May 10 23:52:07 2024
Count: 1
Stack: .../Skin/Interface/SharedXML/Scroll/OribosScrollBar.lua:16: attempt to call field 'FrameTypeScrollBarButton' (a nil value)
[string "=[C]"]: in function `FrameTypeScrollBarButton'
[string "@Interface/AddOns/Aurora/Skin/Interface/SharedXML/Scroll/OribosScrollBar.lua"]:16: in function `OribosScrollBarButtonScripts'
[string "@Interface/AddOns/Aurora/Skin/Interface/SharedXML/Scroll/OribosScrollBar.lua"]:24: in function `OribosScrollBar'
[string "@Interface/AddOns/Aurora/Skin/Interface/AddOns/Blizzard_Soulbinds.lua"]:23: in function `ConduitListTemplate'
[string "@Interface/AddOns/Aurora/Skin/Interface/AddOns/Blizzard_Soulbinds.lua"]:107: in function `addonModule'
[string "@Interface/AddOns/Aurora/Skin/init.lua"]:185: in function <Interface/AddOns/Aurora/Skin/init.lua:149>
[string "=[C]"]: in function `resume'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1286: in function `Login'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1373: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1321>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by arnvid** [comment]
Latest beta might work better...
Working one some changes ..

**Comment by Heregellas** [comment]
Hey !
Unfortunately, I just tested it, and it's still not working :( (as before ; most of the skinning, fonts, etc. are not working)
The LUA errors are the same as my second post (the same 4) while logging in game.

**Comment by arnvid** [comment]
This one?

https://github.com/Gethe/Aurora/releases/tag/10.2.6.1.103-beta

**Comment by arnvid** [comment]
I have run it solo and with realui. Will check tomorrow

**Comment by Freeruns** [comment]
Solo i have this error:
Aurora/aurora.lua:152: hooksecurefunc(): FriendsFrame is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Aurora/aurora.lua"]:152: in function `OnLoad'
[string "@Aurora/Skin/init.lua"]:155: in function <Aurora/Skin/init.lua:149>

Locals:

**Comment by Heregellas** [comment]
Yeah I tested this build (https://github.com/Gethe/Aurora/releases/tag/10.2.6.1.103-beta) and it wasn't working at all unfortunately :(

**Comment by Heregellas** [comment]
I tried running the addon solo (I mean, only Aurora enabled, without any other addon), and yeah I still have the first LUA error of the 4 I put in my second message (the same one that Freeruns has commented 2 days ago, regarding "hooksecurefunc(): FriendsFrame is not a function").
And, on top of the error, nearly nothing is working unfortunately (frames are mostly not skinned (like the Character Panel, for instance, is the basic one), the font is the old ugly Blizzard one, etc.) :(

(Just adding a comment to provide updates just in case, not to rush you in any way of course, no worries at all !)

**Comment by Heregellas** [comment]
Just so to know, do we have en ETA for a fix for this addon yet ? (I know I wrote I didn't want to rush you people, of course, just asking 'cause well, it's been 2 weeks and unfortunately no news after the last message where it was said you'd check the day after)

**Comment by arnvid** [comment]
Been spending time to see if I can reproduce errors etc..I have been playing with the current version for a while on the Pandaria Remix and on mainline/retail wow. Bot standalone and as part of RealUI. generally without errors .. there are 1 error that comes on load that I believe is not part of Aurora - but more something that is caused with remix of pandaria.

**Comment by Heregellas** [comment]
The last update you just pushed minutes ago fixed the hooksecurefunc thing and allows Aurora to skin & change the font, so thank you for that ! <3

Another set of errors is tied to the LFG window skin though. It's just errors, the addon is working besides that, so not as important as the last one, but just in case I'm listing them here (different errors when opening LFG window, tagging, cancelling application, etc).
(On top of that, icons are a bit scuffed, I'll attach a screenshot to show you icons where we can't dissociate roles)

Thanks a lot for the fix, and thanks in advance for the future updates !

https://i.gyazo.com/c960e098a623107d4ccba1b0ea920f24.png


 Message: ...ce/AddOns/Aurora/Skin/Interface/FrameXML/LFGList.lua:66: attempt to index field '_auroraBorder' (a nil value)
Time: Sat May 25 03:12:34 2024
Count: 72
Stack: ...ce/AddOns/Aurora/Skin/Interface/FrameXML/LFGList.lua:66: attempt to index field '_auroraBorder' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/Aurora/Skin/Interface/FrameXML/LFGList.lua"]:66: in function <...ce/AddOns/Aurora/Skin/Interface/FrameXML/LFGList.lua:58>
[string "=[C]"]: in function `LFGListGroupDataDisplayEnumerate_Update'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:3195: in function `LFGListGroupDataDisplay_Update'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:2828: in function `LFGListSearchEntry_Update'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:2350: in function `initializer'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:396: in function `InvokeInitializer'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:405: in function `InvokeInitializers'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:718: in function `Update'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:258: in function `SetScrollPercentageInternal'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:184: in function `FullUpdateInternal'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:692: in function `FullUpdateInternal'
...
[string "@Interface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua"]:178: in function <...rface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua"]:181: in function `TriggerEvent'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:342: in function `SignalDataChangeEvent'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:322: in function `SetDataProvider'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:647: in function `SetDataProvider'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:2394: in function `LFGListSearchPanel_UpdateResults'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:2330: in function `LFGListSearchPanel_UpdateResultList'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:2132: in function `onEvent'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:251: in function <...ace/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua:169>

Locals: (*temporary) = <function> defined =[C]:-1



======= Error 2 ========


Message: ...ce/AddOns/Aurora/Skin/Interface/FrameXML/LFGList.lua:66: attempt to index field '_auroraBorder' (a nil value)
Time: Sat May 25 03:16:53 2024
Count: 42
Stack: ...ce/AddOns/Aurora/Skin/Interface/FrameXML/LFGList.lua:66: attempt to index field '_auroraBorder' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/Aurora/Skin/Interface/FrameXML/LFGList.lua"]:66: in function <...ce/AddOns/Aurora/Skin/Interface/FrameXML/LFGList.lua:58>
[string "=[C]"]: in function `LFGListGroupDataDisplayEnumerate_Update'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:3195: in function `LFGListGroupDataDisplay_Update'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:2828: in function `LFGListSearchEntry_Update'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:2150: in function `onEvent'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:251: in function <...ace/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua:169>

Locals: (*temporary) = <function> defined =[C]:-1


======= Error 3 ========


Message: ...ce/AddOns/Aurora/Skin/Interface/FrameXML/LFGList.lua:66: attempt to index field '_auroraBorder' (a nil value)
Time: Sat May 25 03:10:17 2024
Count: 9
Stack: ...ce/AddOns/Aurora/Skin/Interface/FrameXML/LFGList.lua:66: attempt to index field '_auroraBorder' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/Aurora/Skin/Interface/FrameXML/LFGList.lua"]:66: in function <...ce/AddOns/Aurora/Skin/Interface/FrameXML/LFGList.lua:58>
[string "=[C]"]: in function `LFGListGroupDataDisplayEnumerate_Update'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:3195: in function `LFGListGroupDataDisplay_Update'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:2828: in function `func'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:157: in function `ForEachFrame'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:532: in function `ForEachFrame'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:3889: in function `minRatingChangeCallback'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:3752: in function `OnMinRatingChanged'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:3736: in function <...ace/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua:3735>

Locals: (*temporary) = <function> defined =[C]:-1


======= Error 4 ========


Message: ...ce/AddOns/Aurora/Skin/Interface/FrameXML/LFGList.lua:66: attempt to index field '_auroraBorder' (a nil value)
Time: Sat May 25 03:11:38 2024
Count: 9
Stack: ...ce/AddOns/Aurora/Skin/Interface/FrameXML/LFGList.lua:66: attempt to index field '_auroraBorder' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/Aurora/Skin/Interface/FrameXML/LFGList.lua"]:66: in function <...ce/AddOns/Aurora/Skin/Interface/FrameXML/LFGList.lua:58>
[string "=[C]"]: in function `LFGListGroupDataDisplayEnumerate_Update'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:3195: in function `LFGListGroupDataDisplay_Update'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:2828: in function `LFGListSearchEntry_Update'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:2350: in function `initializer'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:396: in function `InvokeInitializer'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:405: in function `InvokeInitializers'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:718: in function `Update'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:258: in function `SetScrollPercentageInternal'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:184: in function `FullUpdateInternal'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:692: in function `FullUpdateInternal'
...
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua"]:178: in function <...rface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua"]:181: in function `TriggerEvent'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:342: in function `SignalDataChangeEvent'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:322: in function `SetDataProvider'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:647: in function `SetDataProvider'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:2394: in function `LFGListSearchPanel_UpdateResults'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:2142: in function `onEvent'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:251: in function <...ace/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua:169>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by arnvid** [comment]
Tnx.. I will look tomorrow. I ran LFGs with RealUI not plain Aurora.. I might have noticed this one too I  believe.

**Comment by arnvid** [comment]
![image](https://github.com/Gethe/Aurora/assets/876871/b73d56c1-754b-4bf0-b6f3-ccf48790ce4b)

This is how it looks for me.

**Comment by Heregellas** [comment]
Weird ? I even tried once again with only Aurora, and it looked the same as my screenshot 🤔

**Comment by arnvid** [comment]
Oh .. let me recheck

**Comment by arnvid** [comment]
There I found it too.. even with RealUI loaded.. ok..

**Comment by arnvid** [comment]
```
x26  Interface/AddOns/Aurora/Skin/api.lua:220: texture widget expected, got Frame
Stack: [string "=[C]"]: in function 'assert'
[string "@Interface/AddOns/Aurora/Skin/api.lua"]:220: in function 'SetTexture'
[string "@Interface/AddOns/Aurora/Skin/Interface/FrameXML/LFGList.lua"]:77: in function <...ce/AddOns/Aurora/Skin/Interface/FrameXML/LFGList.lua:58>
[string "=[C]"]: in function 'LFGListGroupDataDisplayEnumerate_Update'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:3195: in function 'LFGListGroupDataDisplay_Update'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:2828: in function 'LFGListSearchEntry_Update'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:2350: in function 'initializer'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:396: in function 'InvokeInitializer'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:405: in function 'InvokeInitializers'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:718: in function 'Update'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:258: in function 'SetScrollPercentageInternal'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:184: in function 'FullUpdateInternal'
...
[string "@Interface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua"]:178: in function <...rface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXML/CallbackRegistry.lua"]:181: in function 'TriggerEvent'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:342: in function 'SignalDataChangeEvent'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:322: in function 'SetDataProvider'
[string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:647: in function 'SetDataProvider'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:2394: in function 'LFGListSearchPanel_UpdateResults'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:2330: in function 'LFGListSearchPanel_UpdateResultList'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:2132: in function 'onEvent'
[string "@Interface/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua"]:251: in function <...ace/AddOns/Blizzard_GroupFinder/Mainline/LFGList.lua:169>
Time: 2024/05/26 03:03:09 Index: 1/1
Locals:
(*temporary) = false
(*temporary) = "texture widget expected, got Frame"

```

**Comment by arnvid** [comment]
Fix is not perfect - but it should be working now.
Need to redo the LFGList a bit more for later versions.

**Comment by Heregellas** [comment]
Yeah, it will clearly do as a fix for now, thanks a lot !
