### ISSUE TITLE
[Bug] lua error (aurora not skinning any panels)

### ISSUE THREAD

**Issue by zofia1347** [Gethe/Aurora#118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

With all mods disabled and only Aurora enabled the addon is not skinning a lot of the blizzard panels/windows it should be. For example it won't skin the character panel, spellbook, or lfg. Turned on lua errors to share in case this might be the reason? No idea how to read any of this so any help is appreciated! Thank you for your time :)

Also I am using the latest installation from 10.2.7.1.

> Message: ...rora/Skin/Interface/FrameXML/ActionBarController.lua:575: attempt to index field 'Background' (a nil value)
> Time: Sat Jun  1 20:39:52 2024
> Count: 1
> Stack: ...rora/Skin/Interface/FrameXML/ActionBarController.lua:575: attempt to index field 'Background' (a nil value)
> [string "@Interface/AddOns/Aurora/Skin/Interface/FrameXML/ActionBarController.lua"]:575: in function `?'
> [string "@Interface/AddOns/Aurora/Skin/init.lua"]:166: in function <Interface/AddOns/Aurora/Skin/init.lua:149>
> 
> Locals: MainMenuBar = MainMenuBar {
>  0 = <userdata>
>  QuickKeybindRightShadow = Texture {
>  }
>  GetShowAllButtons = <function> defined @Interface/AddOns/Blizzard_ActionBar/Mainline/ActionBar.lua:173
>  UpdateSystemSettingAlwaysShowButtons = <function> defined @Interface/AddOns/Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:994
>  UpdateMagnetismRegistration = <function> defined @Interface/AddOns/Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:731
>  GetSnapOffsets = <function> defined @Interface/AddOns/Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:609
>  UpdateFrameStrata = <function> defined @Interface/AddOns/Blizzard_ActionBar/Mainline/ActionBar.lua:194
>  IsFrameAnchoredToMe = <function> defined @Interface/AddOns/Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:694
>  TrySetCompositeNumberSettingValue = <function> defined @Interface/AddOns/Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:212
>  downKeys = <table> {
>  }
>  GetFixedSize = <function> defined @Interface/AddOns/Blizzard_SharedXML/LayoutFrame.lua:156
>  buttonTemplate = "MainBarActionBarButtonTemplate"
>  GetFixedWidth = <function> defined @Interface/AddOns/Blizzard_SharedXML/LayoutFrame.lua:148
>  useDefaultAnchors = false
>  GetSelectionOffset = <function> defined @Interface/AddOns/Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:540
>  ResetToDefaultPosition = <function> defined @Interface/AddOns/Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:254
>  oldGridSettings = <table> {
>  }
>  GetScaledSelectionSides = <function> defined @Interface/AddOns/Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:532
>  SelectSystem = <function> defined @Interface/AddOns/Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:763
>  SetFixedWidth = <function> defined @Interface/AddOns/Blizzard_SharedXML/LayoutFrame.lua:135
>  GetFrameMagneticEligibility = <function> defined @Interface/AddOns/Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:714
>  AddLayoutChildren = <function> defined @Interface/AddOns/Blizzard_SharedXML/LayoutFrame.lua:55
>  IsBelowFrame = <function> defined @Interface/AddOns/Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:499
>  UpdateSystemSettingIconSize = <function> defined @Interface/AddOns/Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:933
>  SetFixedSize = <function> defined @Interface/AddOns/Blizzard_SharedXML/LayoutFrame.lua:143
>  HasActiveChanges = <function> defined @Interface/AddOns/Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:381
>  GetScaledCenter = <function> defined @Interface/AddOns/Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:525
>  DoesSettingDisplayValueEqual = <function> defined @Interface/AddOns/Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:445
>  OnLoad = <function> defined @Interface/AddOns/Blizzard_ActionBar/Mainline/MainMenuBar.lua:6
>  UpdateDisplayInfoOptions = <function> defined @Interface/AddOns/Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:456
>  ActionBarPageNumber = Frame {
>  }
>  GetSystemName = <function> defined @Interface/AddOns/Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:822
>  ProcessMovementKey = <function> defined @Interface/AddOns/Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:39
>  GetSettingValueBool = <function> defined @Interface/AddOns/Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:436
>  OnKeyUp = <function> defined @Interface/AddOns/Blizzard_EditMode/Mainline/EditModeSystemTemplates.lua:85
>  IsLayoutFrame = <function> defined @Interface/AddOns/Blizzard_Shared

**Comment by arnvid** [comment]
Use 10.2.7.3
