### ISSUE TITLE
[Issue] Gossip window choices have extremely low visiblity

### ISSUE THREAD

**Issue by morodrim** [Gethe/Aurora#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

It's hard to read the gossip choices when interacting with NPCs.   See screenshot.
![aurora gossip retail](https://github.com/Gethe/Aurora/assets/95843840/cb15fb28-ffc2-401b-9b75-d8f69e857eeb)

### Expected Behavior

Like other Aurora altered UI elements, the contents should be easily visible.

**Comment by zofia1347** [comment]
I believe you can fix this by going to Game Options > Quest Text Contrast > changing it to black. It will make the text on Aurora background.
