### ISSUE TITLE
[Bug] CovenantSanctum

### ISSUE THREAD

**Issue by Vitoshka** [Gethe/Aurora#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

1x ...a/SkinBlizzard_CovenantSanctum.lua:20: attempt to call method 'SetBackdropOption' (a nil value)
[string "@Aurora/SkinBlizzard_CovenantSanctum.lua"]:20: in function <...a/SkinBlizzard_CovenantSanctum.lua:16>
[string "=[C]"]: in function `SetCovenantInfo'
[string "@Blizzard_CovenantSanctum/Blizzard_CovenantSanctum.lua"]:24: in function `InteractionStarted'
[string "@Blizzard_UIPanels_Game/Shared/PlayerInteractionFrameManager.lua"]:138: in function `showFunc'
[string "@Blizzard_UIPanels_Game/Shared/PlayerInteractionFrameManager.lua"]:192: in function `ShowFrame'
[string "@Blizzard_UIPanels_Game/Shared/PlayerInteractionFrameManager.lua"]:230: in function <...Panels_Game/Shared/PlayerInteractionFrameManager.lua:227>

Locals:
self = CovenantSanctumFrame {
 SetCovenantInfo = <function> defined =[C]:-1
 OnShow = <function> defined @Blizzard_CovenantSanctum/Blizzard_CovenantSanctum.lua:13
 GetCovenantData = <function> defined @Blizzard_CovenantSanctum/Blizzard_CovenantSanctum.lua:48
 OnHide = <function> defined @Blizzard_CovenantSanctum/Blizzard_CovenantSanctum.lua:17
 OnLoad = <function> defined @Blizzard_CovenantSanctum/Blizzard_CovenantSanctum.lua:3
 UpgradesTab = Frame {
 }
 covenantID = 1
 CloseButton = Button {
 }
 LevelFrame = Frame {
 }
 NineSlice = Frame {
 }
 0 = <userdata>
 GetCovenantID = <function> defined @Blizzard_CovenantSanctum/Blizzard_CovenantSanctum.lua:44
 covenantData = <table> {
 }
 InteractionStarted = <function> defined @Blizzard_CovenantSanctum/Blizzard_CovenantSanctum.lua:23
}
(*temporary) = nil
(*temporary) = Frame {
 0 = <userdata>
 SetCenterColor = <function> defined @Blizzard_SharedXML/NineSlice.lua:279
 _auroraNineSlice = true
 SetVertexColor = <function> defined @Blizzard_SharedXML/NineSlice.lua:316
 Center = Texture {
 }
 GetBorderColor = <function> defined @Blizzard_SharedXML/NineSlice.lua:304
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 OnLoad = <function> defined @Blizzard_SharedXML/NineSlice.lua:272
 TopEdge = Texture {
 }
 BottomEdge = Texture {
 }
 GetCenterColor = <function> defined @Blizzard_SharedXML/NineSlice.lua:286
 GetFrameLayoutTextureKit = <function> defined @Blizzard_SharedXML/NineSlice.lua:267
 SetBorderBlendMode = <function> defined @Blizzard_SharedXML/NineSlice.lua:321
 BottomRightCorner = Texture {
 }
 GetFrameLayoutType = <function> defined @Blizzard_SharedXML/NineSlice.lua:263
 _applyLayout = true
 BottomLeftCorner = Texture {
 }
 LeftEdge = Texture {
 }
 SetBorderColor = <function> defined @Blizzard_SharedXML/NineSlice.lua:293
}
(*temporary) = "offsets"
(*temporary) = <table> {
 top = 8
 right = 9
 left = 12
 bottom = 17
}
(*temporary) = "attempt to call method 'SetBackdropOption' (a nil value)"
covenantID = 1

**Comment by arnvid** [comment]
What version of Aurora?
How did you get the error?

**Comment by arnvid** [comment]
I am unable to reproduce this.. played around in different areas SL areas.. no errors
