### ISSUE TITLE
[Bug]OribosScrollBar

### ISSUE THREAD

**Issue by Vitoshka** [Gethe/Aurora#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

3x .../Skin/SharedXML/Scroll/OribosScrollBar.lua:16: attempt to call field 'FrameTypeScrollBarButton' (a nil value)
[string "@Aurora/Skin/SharedXML/Scroll/OribosScrollBar.lua"]:16: in function `OribosScrollBarButtonScripts'
[string "@Aurora/Skin/SharedXML/Scroll/OribosScrollBar.lua"]:24: in function `OribosScrollBar'
[string "@Aurora/SkinBlizzard_GarrisonTemplates.lua"]:386: in function `CovenantFollowerListTemplate'
[string "@Aurora/SkinBlizzard_GarrisonUI.lua"]:848: in function `addonModule'
[string "@Aurora/Skin/init.lua"]:186: in function <Aurora/Skin/init.lua:149>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:402: in function `UIParentLoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:599: in function `Garrison_LoadUI'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:2021: in function <...rfaceBlizzard_UIParent/Mainline/UIParent.lua:1304>

Locals:
Frame = Button {
 0 = <userdata>
 OnEnter = <function> defined @Blizzard_SharedXML/ButtonStateBehavior.lua:56
 OnClick_Intrinsic = <function> defined @Blizzard_SharedXML/Shared/Frame/EventButton.lua:56
 IsDown = <function> defined @Blizzard_SharedXML/ButtonStateBehavior.lua:48
 desaturateIfDisabled = true
 Hide = <function> defined =[C]:-1
 GenerateCallbackEvents = <function> defined @Blizzard_SharedXML/CallbackRegistry.lua:216
 DoesFrameHaveEvent = <function> defined @Blizzard_SharedXML/CallbackRegistry.lua:229
 callbackTables = <table> {
 }
 RegisterCallback = <function> defined @Blizzard_SharedXML/CallbackRegistry.lua:110
 OnButtonStateChanged = <function> defined @Blizzard_SharedXML/Mainline/Scroll/OribosScrollBar.lua:9
 SetUndefinedEventsAllowed = <function> defined @Blizzard_SharedXML/CallbackRegistry.lua:77
 UnregisterCallback = <function> defined @Blizzard_SharedXML/CallbackRegistry.lua:185
 OnSizeChanged_Intrinsic = <function> defined @Blizzard_SharedXML/Shared/Frame/EventButton.lua:73
 RegisterCallbackWithHandle = <function> defined @Blizzard_SharedXML/CallbackRegistry.lua:154
 Down = Texture {
 }
 OnMouseDown_Intrinsic = <function> defined @Blizzard_SharedXML/Shared/Frame/EventButton.lua:49
 IsDownOver = <function> defined @Blizzard_SharedXML/ButtonStateBehavior.lua:44
 GetCallbackTables = <function> defined @Blizzard_SharedXML/CallbackRegistry.lua:81
 OnMouseUp = <function> defined @Blizzard_SharedXML/ButtonStateBehavior.lua:91
 Show = <function> defined =[C]:-1
 UnregisterEvents = <function> defined @Blizzard_SharedXML/CallbackRegistry.lua:200
 OnEnter_Intrinsic = <function> defined @Blizzard_SharedXML/Shared/Frame/EventButton.lua:63
 IsOver = <function> defined @Blizzard_SharedXML/ButtonStateBehavior.lua:52
 OnMouseDown = <function> defined @Blizzard_SharedXML/ButtonStateBehavior.lua:74
 _auroraThumb = Frame {
 }
 TriggerEvent = <function> defined @Blizzard_SharedXML/CallbackRegistry.lua:159
 Enter = Texture {
 }
 OnDisable = <function> defined @Blizzard_SharedXML/ButtonStateBehavior.lua:117
 mouseDownSoundKitID = 1115
 DesaturateIfDisabled = <function> defined @Blizzard_SharedXML/ButtonStateBehavior.lua:36
 OnLoad = <function> defined @Blizzard_SharedXML/Mainline/Scroll/OribosScrollBar.lua:3
 OnLeave = <function> defined @Blizzard_SharedXML/ButtonStateBehavior.lua:65
 SetDisplacedRegions = <function> defined @Blizzard_SharedXML/ButtonStateBehavior.lua:29
 Event = <table> {
 }
 GetCallbackTable = <function> defined @Blizzard_SharedXML/CallbackRegistry.lua:85
 OnMouseUp_Intrinsic = <function> defined @Blizzard_SharedXML/Shared/Frame/EventButton.lua:44
 OnEnable = <function> defined @Blizzard_SharedXML/ButtonStateBehavior.lua:109
 HasRegistrantsForEvent = <function> defined @Blizzard_SharedXML/CallbackRegistry.lua:94
 GetCallbacksByEvent = <function> defined @Blizzard_SharedXML/CallbackRegistry.lua:89
 OnLeave_Intrinsic = <function> defined @Blizzard_SharedXML/Shared/Frame/EventButton.lua:69
 OnLoad_Intrinsic = <function> defined @Blizzard_SharedXML/Shared/Frame/EventButton.lua:40
 SecureInsertEvent = <function> defined @Blizzard_SharedXML/CallbackRegistry.lua:104
}
(*temporary) = nil
(*temporary) = Button {
 0 = <userdata>
 OnEnter = <function> defined @Blizzard_SharedXML/ButtonStateBehavior.lua:56
 OnClick_Intrinsic = <function> defined @Blizzard_SharedXML/Shared/Frame/EventButton.lua:56
 IsDown = <function> defined @Blizzard_SharedXML/ButtonStateBehavior.lua:48
 desaturateIfDisabled = true
 Hide = <functi

**Comment by arnvid** [comment]
What version of Aurora?
How did you get the error?

**Comment by arnvid** [comment]
I am unable to reproduce this.. played around in different areas SL areas.. no errors
