### ISSUE TITLE
[Bug]SkinBlizzard_AdventureMap

### ISSUE THREAD

**Issue by Vitoshka** [Gethe/Aurora#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

3x ...rora/SkinBlizzard_AdventureMap.lua:58: attempt to call field 'UIPanelScrollUpButtonTemplate' (a nil value)
[string "@Aurora/SkinBlizzard_AdventureMap.lua"]:58: in function `addonModule'
[string "@Aurora/Skin/init.lua"]:186: in function <Aurora/Skin/init.lua:149>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:402: in function `UIParentLoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:599: in function `Garrison_LoadUI'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:2021: in function <...rfaceBlizzard_UIParent/Mainline/UIParent.lua:1304>

Locals:
AdventureMapQuestChoiceDialog = AdventureMapQuestChoiceDialog {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Aurora/Skin/backdrop.lua:175
 Center = Texture {
 }
 GetBackdropColor = <function> defined @Aurora/Skin/backdrop.lua:285
 SetBackdropOptions = <function> defined @Aurora/Skin/backdrop.lua:364
 RightEdge = Texture {
 }
 LeftEdge = Texture {
 }
 SetBackdropBorderColor = <function> defined @Aurora/Skin/backdrop.lua:289
 DeclineQuest = <function> defined @Blizzard_AdventureMap/AM_QuestDialog.lua:200
 BottomEdge = Texture {
 }
 TopEdge = Texture {
 }
 GetBackdropTexture = <function> defined @Aurora/Skin/backdrop.lua:333
 RewardsHeader = FontString {
 }
 BottomRightCorner = Texture {
 }
 Details = ScrollFrame {
 }
 Rewards = Texture {
 }
 SetBackdrop = <function> defined @Aurora/Skin/backdrop.lua:246
 ClearBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:282
 BottomLeftCorner = Texture {
 }
 GetBackdropBorderColor = <function> defined @Aurora/Skin/backdrop.lua:305
 GetBackdrop = <function> defined @Blizzard_SharedXML/Backdrop.lua:347
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 RefreshDetails = <function> defined @Blizzard_AdventureMap/AM_QuestDialog.lua:173
 FadeIn = AnimationGroup {
 }
 SetBackdropGradient = <function> defined @Aurora/Skin/backdrop.lua:311
 RefreshRewards = <function> defined @Blizzard_AdventureMap/AM_QuestDialog.lua:95
 Finalize = <function> defined @Blizzard_AdventureMap/AM_QuestDialog.lua:73
 Portrait = Texture {
 }
 backdropInfo = <table> {
 }
 _backdropInfo = <table> {
 }
 SetBackdropLayer = <function> defined @Aurora/Skin/backdrop.lua:319
 GetBackdropLayer = <function> defined @Aurora/Skin/backdrop.lua:328
 DeclineButton = Button {
 }
 OnParentHide = <function> defined @Blizzard_AdventureMap/AM_QuestDialog.lua:12
 OnShow = <function> defined @Blizzard_AdventureMap/AM_QuestDialog.lua:62
 SetupTextureCoordinates = <function> defined @Blizzard_SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Blizzard_SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Blizzard_SharedXML/Backdrop.lua:278
 Background = Texture {
 }
 AddReward = <function> defined @Blizzard_AdventureMap/AM_QuestDialog.lua:142
 AcceptButton = Button {
 }
 ApplyBackdrop = <function> defined @Aurora/Skin/backdrop.lua:193
 GetEdgeSize = <function> defined @Blizzard_SharedXML/Backdrop.lua:188
 GetBackdropOption = <function> defined @Aurora/Skin/backdrop.lua:358
 OnLoad = <function> defined @Blizzard_AdventureMap/AM_QuestDialog.lua:8
 OnHide = <function> defined @Blizzard_AdventureMap/AM_QuestDialog.lua:67
 Refresh = <function> defined @Blizzard_AdventureMap/AM_QuestDialog.lua:83
 AcceptQuest = <function> defined @Blizzard_AdventureMap/AM_QuestDialog.lua:194
 OnEvent = <function> defined @Blizzard_AdventureMap/AM_QuestDialog.lua:53
 SetBorderBlendMode = <function> defined @Blizzard_SharedXML/Backdrop.lua:266
 ShowWithQuest = <function> defined @Blizzard_AdventureMap/AM_QuestDialog.lua:18
 SetBackdropOption = <function> defined @Aurora/Skin/backdrop.lua:342
 rewardPool = <table> {
 }
 SetupPieceVisuals = <function> defined @Aurora/Skin/backdrop.lua:178
 SetBackdropColor = <function> defined @Aurora/Skin/backdrop.lua:275
 SetPortraitAtlas = <function> defined @Blizzard_AdventureMap/AM_QuestDialog.lua:43
 CloseButton = Button {
 }
}
ScrollBar = Frame {
 0 = <userdata>
 UnregisterUpdate = <function> defined @Blizzard_SharedXML/Shared/Scroll/ScrollBa

**Comment by arnvid** [comment]
What version of Aurora?
How did you get the error?

**Comment by arnvid** [comment]
I am unable to reproduce this.. played around in different areas SL areas.. no errors
