### ISSUE TITLE
[Qustion]Update for TWW?

### ISSUE THREAD

**Issue by mstoczko** [Gethe/Aurora#127]
I love this addon and I'm curious if it will be updated for TWW expansion? Thanks!

**Comment by arnvid** [comment]
I have an WIP version that is kinda an alpha. Might plug some stuff to push a low/no-error version out. It used in the RealUI alpha.

**Comment by mstoczko** [comment]
That would be awesome...let me know!

**Comment by arnvid** [comment]
I have released a "starting" version for TWW. please give feedback =)
