### ISSUE TITLE
[Bug] Error when moving CollectionsJournal window

### ISSUE THREAD

**Issue by arnvid** [Gethe/Aurora#13]
**Describe the bug**
Error when moving CollectionsJournal window

**To Reproduce**
1. Press Shift P
2. Try to move the window
3. See error

**Screenshots**
x1  RealUI_Core-2.3.0\Util.lua:95: attempt to perform arithmetic on local 'value' (a nil value)
Stack: [string "@RealUI_Core-2.3.0\Util.lua"]:95: in function 'Round'
[string "@RealUI_Core-2.3.0\Util.lua"]:368: in function 'SetPixelPoint'
[string "@RealUI_Core-2.3.0\Core\FramePoint.lua"]:81: in function <RealUI_Core-2.3.0\Core\FramePoint.lua:80>
Time: 2021/11/29 11:39:53 Index: 3/3
Locals:
value = nil
places = nil
mult = 1
(*temporary) = function =[C]
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'value' (a nil value)"

**Additional context**
In 9.1.x the Blizzard_Collections\ changed and it is now a dynamic window (?) - which does not return anything on frame:GetPoint()

function RealUI.SetPixelPoint(frame)
    local point, anchor, relPoint, x, y = frame:GetPoint()
    if not point then
        print("setpixel on invalid frame", frame:GetName())
        -- print("debug frame", dumpxyz(frame))
    end
    local modx, modY = RealUI.Round(x), RealUI.Round(y)

**Comment by Gethe** [comment]
This is not an issue with Aurora.

**Comment by arnvid** [comment]
Seems to be caused by LibWindow-1.1

**Comment by arnvid** [comment]
Added workaround in my fork for now
[dev_9_1_5 65ebdfc7] fix: nibRealUI/Modules/DragEmAll.lua - disabled dragging for CollectionJournal
