### ISSUE TITLE
[Bug] options ui (/aurora) doesnt work in game

### ISSUE THREAD

**Issue by FatihYagci** [Gethe/Aurora#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

everytime i write /aurora it just opens the options of wow.

### Expected Behavior

to open aurora addons settings.

### Steps To Reproduce

/aurora in game
wow settings panel opens up

**Comment by arnvid** [comment]
This have been fixed now
