### ISSUE TITLE
[Bug] Error when opening Adventure Guide

### ISSUE THREAD

**Issue by Epidemedabear** [Gethe/Aurora#14]
This is a bug report but I cant create a bug report for some reason 

When opening the Adventure Guide I get the following error

1x Aurora\Skin\api.lua:79: attempt to index local 'texture' (a nil value)
[string "@Aurora\Skin\api.lua"]:79: in function `CropIcon'
[string "@Aurora\SkinBlizzard_EncounterJournal-1.0.lua"]:280: in function `?'
[string "@Aurora\Skin\SharedXML\HybridScrollFrame.lua"]:19: in function <...urora\Skin\SharedXML\HybridScrollFrame.lua:12>
[string "=[C]"]: in function `HybridScrollFrame_CreateButtons'
[string "@Blizzard_EncounterJournal\Blizzard_EncounterJournal-1.0.lua"]:227: in function <...zzard_EncounterJournal\Blizzard_EncounterJournal.lua:198>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:509: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:667: in function `EncounterJournal_LoadUI'
[string "@FrameXML\UIParent.lua"]:1067: in function `ToggleEncounterJournal'
[string "@FrameXML\MainMenuBarMicroButtons.lua"]:1238: in function <FrameXML\MainMenuBarMicroButtons.lua:1236>
[string "=[C]"]: ?

Locals:
texture = nil
parent = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'texture' (a nil value)"

**Comment by arnvid** [comment]
`EncounterItemTemplate on invalid Button:  { [0] = userdata: 000001A9C0767EA8,["dividerFrame"] = { [0] = userdata: 000001AA2F1C8E28,["TipButton"] = { [0] = userdata: 000001AAB201D3A8,["I"] = { [0] = userdata: 000001AACA011538,} ,} ,["name"] = { [0] = userdata: 000001AA27D03598,} ,} ,["lootFrame"] = { [0] = userdata: 000001AAC43133A8,["bossTexture"] = { [0] = userdata: 000001AACA0123B8,} ,["slot"] = { [0] = userdata: 000001AA27D03B58,} ,["IconOverlay"] = { [0] = userdata: 000001AACA014F38,} ,["bosslessTexture"] = { [0] = userdata: 000001AACA012018,} ,["boss"] = { [0] = userdata: 000001AA27D03878,} ,["name"] = { [0] = userdata: 000001AA27D02A18,} ,["IconBorder"] = { [0] = userdata: 000001AACA011C78,} ,["IconOverlay2"] = { [0] = userdata: 000001AACA0118D8,} ,["icon"] = { [0] = userdata: 000001AACA012758,} ,["armorType"] = { [0] = userdata: 000001AA27D02738,} ,} ,} `

**Comment by arnvid** [comment]
DEBUG: Button has no icon ?! -  EncounterJournalEncounterFrameInfoLootScrollFrameButton1
DEBUG: Button has no icon ?! -  EncounterJournalEncounterFrameInfoLootScrollFrameButton2
DEBUG: Button has no icon ?! -  EncounterJournalEncounterFrameInfoLootScrollFrameButton3
DEBUG: Button has no icon ?! -  EncounterJournalEncounterFrameInfoLootScrollFrameButton4
DEBUG: Button has no icon ?! -  EncounterJournalEncounterFrameInfoLootScrollFrameButton5
DEBUG: Button has no icon ?! -  EncounterJournalEncounterFrameInfoLootScrollFrameButton6
DEBUG: Button has no icon ?! -  EncounterJournalEncounterFrameInfoLootScrollFrameButton7
DEBUG: Button has no icon ?! -  EncounterJournalEncounterFrameInfoLootScrollFrameButton8
DEBUG: Button has no icon ?! -  EncounterJournalEncounterFrameInfoLootScrollFrameButton9
DEBUG: Button has no icon ?! -  EncounterJournalEncounterFrameInfoLootScrollFrameButton10

**Comment by arnvid** [comment]
Found and fixed this one - comming to PR
