### ISSUE TITLE
[Bug] Error on LFG Frame

### ISSUE THREAD

**Issue by Zapa289** [Gethe/Aurora#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

TBC Classic

### Current Behavior

LUA error on load in. LFG frame is unskinned. Looks like _G.LFGParentFrame is nil at the time when this script runs for some reason.

### Expected Behavior

LFG frame is skinned.

### Steps To Reproduce

Log in.

### Additional context

Message: Interface\AddOns\Aurora\Skin\backdrop.lua:386: attempt to index local 'frame' (a nil value)
Time: Wed Jan 19 22:05:22 2022
Count: 1
Stack: Interface\AddOns\Aurora\Skin\backdrop.lua:386: attempt to index local 'frame' (a nil value)
[string "@Interface\AddOns\Aurora\Skin\backdrop.lua"]:386: in function `SetBackdrop'
[string "@Interface\AddOns\Aurora\Skin\skin.lua"]:15: in function `FrameTypeFrame'
[string "@Interface\AddOns\Aurora\Skin\Classic\Interface_TBC\FrameXML\LFGFrame.lua"]:34: in function `?'
[string "@Interface\AddOns\Aurora\Skin\init.lua"]:247: in function <Interface\AddOns\Aurora\Skin\init.lua:228>

Locals: frame = nil
color = <table> {
 a = 0.200000
 colorStr = "ff000000"
 b = 0
 Lightness = <function> defined @Interface\AddOns\Aurora\Skin\color.lua:71
 g = 0
 GetRGBA = <function> defined @Interface\SharedXML\Color.lua:28
 Saturation = <function> defined @Interface\AddOns\Aurora\Skin\color.lua:65
 SetRGB = <function> defined @Interface\SharedXML\Color.lua:43
 Hue = <function> defined @Interface\AddOns\Aurora\Skin\color.lua:59
 GetRGB = <function> defined @Interface\SharedXML\Color.lua:20
 r = 0
 GenerateHexColorMarkup = <function> defined @Interface\SharedXML\Color.lua:51
 WrapTextInColorCode = <function> defined @Interface\SharedXML\Color.lua:55
 GenerateHexColor = <function> defined @Interface\SharedXML\Color.lua:47
 IsEqualTo = <function> defined @Interface\AddOns\Aurora\Skin\color.lua:42
 isAchromatic = true
 SetRGBA = <function> defined @Interface\AddOns\Aurora\Skin\color.lua:29
 OnLoad = <function> defined @Interface\SharedXML\Color.lua:9
 GetRGBAsBytes = <function> defined @Interface\SharedXML\Color.lua:24
 GetRGBAAsBytes = <function> defined @Interface\SharedXML\Color.lua:32
}
alpha = 0.700000
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'frame' (a nil value)"
Base = <table> {
 SetHighlight = <function> defined @Interface\AddOns\Aurora\Skin\deprecated.lua:14
 SetTexture = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:214
 SetFont = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:90
 IsTextureRegistered = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:210
 SetBackdropColor = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:392
 SetBackdrop = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:385
 CropIcon = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:78
 GetAddonSkins = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:55
 AddSkin = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:39
 CreateBackdrop = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:366
 RegisterTexture = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:224
}
backdrop = <table> {
 bgFile = "Interface\Buttons\WHITE8x8"
 tile = true
 backdropBorderSubLevel = -7
 offsets = <table> {
 }
 backdropSubLevel = -8
 edgeFile = "Interface\Buttons\WHITE8x8"
 backdropBorderLayer = "BACKGROUND"
 backdropLayer = "BACKGROUND"
 edgeSize = 1
 insets = <table> {
 }
}

**Comment by Gethe** [comment]
Fixed the beta version
