### ISSUE TITLE
[Bug] Pet Battles don't have a background, should they?

### ISSUE THREAD

**Issue by ZINK-ZINK** [Gethe/Aurora#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

latest beta from wowinterface AFAIK...

https://imgur.com/SPLUPxs

i wasn't sure if there should be a background texture behind the Pet Battle Icons

**Comment by Gethe** [comment]
Yes this is intended
