### ISSUE TITLE
[Bug] Patch 9.1.5 | UI not showing in these specific windows: Character window, Spellbook, Group Finder, etc.

### ISSUE THREAD

**Issue by msyanig** [Gethe/Aurora#2]
**Describe the bug**
As soon as I updated for the new patch 9.1.5 released on EU today, the Aurora UI is no longer showing up on some windows so I now have the Blizzard UI for my character window, chatbox, spellbook, group finder, game menu. I have "Load out of date addons" enabled. I uninstalled and reinstalled the addon, nothing changed.

**Expected behavior**
For Aurora addon to fully work on all windows and still be showing as my UI.

**Screenshots**
![Screenshot_34](https://user-images.githubusercontent.com/43123100/140088144-686ed3bf-36a8-4493-ab3c-b9f2da3b73f3.png)
![Screenshot_36](https://user-images.githubusercontent.com/43123100/140088159-d48503a0-9a07-490f-ada0-a33c3f2cb267.png)
![Screenshot_37](https://user-images.githubusercontent.com/43123100/140088163-feb25aff-6c8b-4a63-bca1-2db7dbd2ea4f.png)

**Comment by hobulian** [comment]
Totally broken now.
