### ISSUE TITLE
[Bug] Guild Bank Hotfix left out of recent update? 

### ISSUE THREAD

**Issue by ZINK-ZINK** [Gethe/Aurora#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

I may have updated from the wrong source, but I believe I'm on the latest beta from WoWInterface. I think the guild bank fix you applied a few weeks ago got left out of the latest beta since it's gone again for me. 

BTW I love that new Revendreth background at the anima turn in npc. At least I think it's new, I definitely went "woah when did it look this cool" and I'm pretty sure you're responsible so great job! heh

**Comment by Gethe** [comment]
If you go to the addon interface options, what version does it have at the top of the Aurora section?
