### ISSUE TITLE
[Bug] 9.2 - Lua errors

### ISSUE THREAD

**Issue by Heregellas** [Gethe/Aurora#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

Some Lua errors since the new patch, that happen during like MM+ and raids, regularly.

`Message: Interface\AddOns\Aurora\Skin\skin.lua:46: Usage: hooksecurefunc([table,] "function", hookfunc)
Time: Sat Feb 26 14:49:29 2022
Count: 1
Stack: Interface\AddOns\Aurora\Skin\skin.lua:46: Usage: hooksecurefunc([table,] "function", hookfunc)
[string "=[C]"]: ?
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface\AddOns\Aurora\Skin\skin.lua"]:46: in function <Interface\AddOns\Aurora\Skin\skin.lua:45>
[string "=[C]"]: in function `FrameTypeButton'
[string "@Interface\AddOns\Aurora\Skin\Interface\AddOns\Blizzard_PVPUI.lua"]:111: in function `PVPCasualActivityButton'
[string "@Interface\AddOns\Aurora\Skin\Interface\AddOns\Blizzard_PVPUI.lua"]:123: in function `PVPCasualSpecialEventButtonTemplate'
[string "@Interface\AddOns\Aurora\Skin\Interface\AddOns\Blizzard_PVPUI.lua"]:174: in function `addonModule'
[string "@Interface\AddOns\Aurora\Skin\init.lua"]:267: in function <Interface\AddOns\Aurora\Skin\init.lua:228>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:529: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\PVEFrame.lua"]:120: in function `PVEFrame_ShowFrame'
[string "@Interface\FrameXML\PVEFrame.lua"]:163: in function <Interface\FrameXML\PVEFrame.lua:161>`

`Message: Interface\SharedXML\NineSlice.lua:227: Attempt to access forbidden object from code tainted by an AddOn
Time: Sat Feb 26 15:53:58 2022
Count: 1
Stack: Interface\SharedXML\NineSlice.lua:227: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: ?
[string "=[C]"]: in function `SetVertexColor'
[string "@Interface\SharedXML\NineSlice.lua"]:227: in function `SetCenterColor'
[string "@Interface\AddOns\Aurora\Skin\Interface\SharedXML\SharedTooltipTemplates.lua"]:18: in function <...\Skin\Interface\SharedXML\SharedTooltipTemplates.lua:13>
[string "=[C]"]: in function `SharedTooltip_SetBackdropStyle'
[string "@Interface\FrameXML\GameTooltip.lua"]:413: in function <Interface\FrameXML\GameTooltip.lua:409>
[string "=[C]"]: in function `Hide'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:646: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:645>
`

If you know how to fix this, it'll be very nice ! Thanks a lot in advance ! <3

### Expected Behavior

To have 0 lua errors \o/

### Steps To Reproduce

It happened during MM+ & raids, randormly and regularly (mostly in raids)

**Comment by Gethe** [comment]
I haven't had a chance to replicate these errors, but please try the latest beta and see if they still pop up.

**Comment by Heregellas** [comment]
Hey,
Sure thing, will try it and tell you if there is any problem :)

Thanks, and have a nice day ! :)

**Comment by Heregellas** [comment]
Actually, with the new version, I got this error right after logging in :

`Message: Error loading Interface\AddOns\Aurora\Skin\Interface\AddOns\Blizzard_PlayerChoice.lua
Time: Sun Feb 27 15:55:03 2022
Count: 4`


If you know how to handle that ! :D

**Comment by Heregellas** [comment]
So yeah I still have the same lua errors in raid even with the new version it seems :(
