### ISSUE TITLE
SharedUIPanelTemplates.lua:395: attempt to index local 'Frame' (a nil value) [Bug]

### ISSUE THREAD

**Issue by iOut1aw** [Gethe/Aurora#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

Message: ...\Skin\Interface\SharedXML\SharedUIPanelTemplates.lua:395: attempt to index local 'Frame' (a nil value)
Time: Wed Mar 16 23:23:25 2022
Count: 1
Stack: ...\Skin\Interface\SharedXML\SharedUIPanelTemplates.lua:395: attempt to index local 'Frame' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Aurora\Skin\Interface\SharedXML\SharedUIPanelTemplates.lua"]:395: in function `NineSlicePanelTemplate'
[string "@Interface\AddOns\Aurora\Skin\Interface\SharedXML\SharedUIPanelTemplates.lua"]:504: in function `TooltipBackdropTemplate'
[string "@Interface\AddOns\RCLootCouncil\Libs\MSA-DropDownMenu-1.0\MSA-DropDownMenu-1.0.lua"]:1704: in function <...l\Libs\MSA-DropDownMenu-1.0\MSA-DropDownMenu-1.0.lua:1700>
[string "@Interface\AddOns\RCLootCouncil\Libs\MSA-DropDownMenu-1.0\MSA-DropDownMenu-1.0.lua"]:1714: in function <...l\Libs\MSA-DropDownMenu-1.0\MSA-DropDownMenu-1.0.lua:1711>

Locals: 

### Expected Behavior

No error

### Steps To Reproduce

Just login in game :)

**Comment by Gethe** [comment]
RCLootCouncil is using an old version of MSA-DropDownMenu. I would bring this up with them.
