### ISSUE TITLE
[Bug] Nothing being skinned

### ISSUE THREAD

**Issue by Zapa289** [Gethe/Aurora#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

TBC Classic

### Current Behavior

Aurora fails to skin most things after throwing LUA errors while trying to skin the Interface options.

### Expected Behavior

Most menus and panels should be skinned.

### Steps To Reproduce

1. Open character panel. Nothing is skinned.

**Comment by Mulle9000** [comment]
this is still happening on the current version of TBC.

**Comment by Jeremy7600** [comment]
This is still broken on the latest release.
