### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Mulle9000** [Gethe/Aurora#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

TBC Classic

### Current Behavior

seems like nothing is reskinned but the LFG tool.

### Expected Behavior

to reskin every window in my interface

### Steps To Reproduce

1. open any window such as character info, spellbook or skill window.
2. see that nothing is reskinned.

**Comment by Gethe** [comment]
Duplicate
