### ISSUE TITLE
[Bug] Get the following errors in 9.2.5 using latest version

### ISSUE THREAD

**Issue by Epidemedabear** [Gethe/Aurora#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

5x ...urora\Skin\FrameXML\StaticPopupSpecial.lua:17: attempt to index local 'Frame' (a nil value)
[string "@Aurora\Skin\FrameXML\StaticPopupSpecial.lua"]:17: in function `PlayerReportFrameTemplate'
[string "@Aurora\Skin\FrameXML\StaticPopupSpecial.lua"]:57: in function `?'
[string "@Aurora\Skin\init.lua"]:250: in function <Aurora\Skin\init.lua:231>

Locals:
Frame = nil
(*temporary) = <function> defined @Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:417
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'Frame' (a nil value)"
Skin = <table> {
 AchievementHeaderStatusBarTemplate = <function> defined @Aurora\SkinBlizzard_AchievementUI.lua:257
 LFGSpecificChoiceTemplate = <function> defined @Aurora\Skin\FrameXML\LFGFrame.lua:125
 GuildChallengeAlertFrameTemplate = <function> defined @Aurora\Skin\FrameXML\AlertFrameSystems.lua:219
 PopupButtonTemplate = <function> defined @Aurora\Skin\FrameXML\ItemButtonTemplate.lua:271
 PetBattleUnitTooltipAuraTemplate = <function> defined @Aurora\SkinBlizzard_PetBattleUI.lua:86
 AuctionHouseAuctionsFrameTemplate = <function> defined @Aurora\SkinBlizzard_AuctionHouseUI.lua:438
 AuctionHouseItemDisplayBaseTemplate = <function> defined @Aurora\SkinBlizzard_AuctionHouseUI.lua:201
 AchievementAlertFrameTemplate = <function> defined @Aurora\Skin\FrameXML\AlertFrameSystems.lua:121
 UnitPopupVoiceToggleButtonTemplate = <function> defined @Aurora\Skin\FrameXML\UnitPopupCustomControls.lua:15
 InputBoxInstructionsTemplate = <function> defined @Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:650
 ComparisonPlayerTemplate = <function> defined @Aurora\SkinBlizzard_AchievementUI.lua:339
 OptionsListButtonTemplate = <function> defined @Aurora\Skin\SharedXML\OptionsFrameTemplates.lua:31
 MoneyInputFrameTemplate = <function> defined @Aurora\Skin\FrameXML\MoneyInputFrame.lua:16
 HybridScrollBarTemplate = <function> defined @Aurora\Skin\SharedXML\HybridScrollFrame.lua:43
 ChannelButtonHeaderTemplate = <function> defined @Aurora\SkinBlizzard_Channels.lua:49
 QuickJoinToastTemplate = <function> defined @Aurora\Skin\FrameXML\QuickJoinToast.lua:34
 ContainerFrameHelpBoxTemplate = <function> defined @Aurora\Skin\FrameXML\ContainerFrame.lua:68
 MultiBar1ButtonTemplate = <function> defined @Aurora\Skin\FrameXML\ActionBarController.lua:334
 PvpRoleStatusTemplate = <function> defined @Aurora\Skin\FrameXML\PvpPopup.lua:47
 AuctionHouseDialogButtonTemplate = <function> defined @Aurora\SkinBlizzard_AuctionHouseUI.lua:509
 CommunitiesTicketManagerScrollFrameTemplate = <function> defined @Aurora\SkinBlizzard_Communities.lua:439
 ButtonFrameTemplateMinimizable = <function> defined @Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:488
 MaximizeMinimizeButtonFrameTemplate = <function> defined @Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:669
 UIPanelScrollDownButtonTemplate = <function> defined @Aurora\Skin\SharedXML\SecureUIPanelTemplates.lua:69
 GarrisonFollowerMissionPortraitTemplate = <function> defined @Aurora\SkinBlizzard_GarrisonUI.lua:48
 QuestInfoSpellHeaderTemplate = <function> defined @Aurora\Skin\FrameXML\QuestInfo.lua:210
 ChatConfigBoxTemplate = <function> defined @Aurora\Skin\FrameXML\ChatConfigFrame.lua:55
 ColumnDisplayButtonNoScriptsTemplate = <function> defined @Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:720
 ColorSwatchTemplate = <function> defined @Aurora\Skin\SharedXML\UIDropDownMenu.lua:144
 CollectionsProgressBarTemplate = <function> defin

==========

5x Aurora\Skin\skin.lua:46: Usage: hooksecurefunc([table,] "function", hookfunc)
[string "=[C]"]: in function `hooksecurefunc'
[string "@Aurora\Skin\skin.lua"]:46: in function <Aurora\Skin\skin.lua:45>
[string "=[C]"]: in function `FrameTypeButton'
[string "@Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua"]:519: in function `UIMenuButtonStretchTemplate'
[string "@Aurora\SkinBlizzard_Collections-1.0.lua"]:747: in function `addonModule'
[string "@Aurora\Skin\init.lua"]:270: in function <Aurora\Skin\init.lua:231>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@Rarity\Core\Collections-Collections.lua"]:63: in function `ScanToys'
[string "@Rarity\Core\Collections-Collections.lua"]:282: in function `ScanExistingItems'
[string "@Rarity\Core.lua"]:175: in function `DoEnable'
[string "@Rarity\Core.lua"]:151: in function <Rarity\Core.lua:150>
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals:
(*temporary) = <table> {
 ContainerFrame5Item7 = ContainerFrame5Item7 {
 }
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 759
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 HealBot_BarButtonIconFadeStartTime_OnValueChanged = <function> defined @HealBot_Options\HealBot_Options.lua:2748
 BT4Button58 = BT4Button58 {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 PawnItemComparer = <function> defined @Pawn\Pawn.lua:3967
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture {
 }
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 359
 MerchantItem5AltCurrencyFrameItem1Text = MerchantItem5AltCurrencyFrameItem1Text {
 }
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 CHAT_HEADER_SUFFIX = ": "
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 COVENANT_MISSIONS_HEALTH = "Health"
 HealBot_Debug_FrameText31 = HealBot_Debug_FrameText31 {
 }
 PaperDollTitlesPaneButton12BgTop = PaperDollTitlesPaneButton12BgTop {
 }
 DUNGEON_FLOOR_UPPERBLACKROCKSPIRE3 = "Hall of Blackhand"
 BT4Button22Flash = BT4Button22Flash {
 }
 MoneyFrame_OnEvent = <function> defined @FrameXML\MoneyFrame.lua:202
 AceConfigDialogTooltipTexture20 = AceConfigDialogTooltipTexture20 {
 }
 CinematicFrameRaidBossEmoteFrame = CinematicFrameRaidBossEmoteFrame {
 }
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 33
 SpellButton6Cooldown = SpellButton6Cooldown {
 }
 ToggleEncounterJournal = <function> defined @FrameXML\UIParent.lua:1107
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 Graphics_QualityText = Graphics_QualityText {
 }
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 FriendsFriendsScrollFrameButton14 = FriendsFriendsScrollFrameButton14 {
 }
 CompactUnitFrameProfilesSaveButton = CompactUnitFrameProfilesSaveButton {
 }
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 HEALBOT_OPTIONS_CPLOGONDURATION = "Crash Protection duration after logon"
 HealBot_IconRCScale_OnValueChanged = <function> defined @HealBot_Options\HealBot_Options.lua:5921
 TitanPanelVolumeControlFrameDialogTitle = TitanPanelVolumeControlFrameDialogTitle {
 }
 CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle = CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle {
 }
 TutorialFrame_OnMouseDown = <function> defined @FrameXML\TutorialFrame.lua:376
 ContainerFrame4Item16Cooldown = ContainerFrame4Item16Cooldown {
 }
 LE_GAME_ERR_AZERITE_ESSENCE_SELECTION_FAILED_ESSENCE_NOT_UNLOCKED = 1038
 DUNGEON_FLOOR_DRAGONBLIGHTCHROMIESCENARIO2 = "Andorhal"
 AudioOptionsVoicePanel_OnShow = <function> defined @SharedXML\AudioOptionsPanelsVoice.lua:49
 L = <table> {
 }
 HealBot_Options_OverridePlayerTargetFramesText = HealBot_Options_OverridePlayerTargetFramesText {
 }
 WL_DESC_LOCATION = "Show/hide your location in a movable tooltip."
 WowTokenRedemptionFrameBg = WowTokenRedemptionFrameBg {
 }
 HEALBOT_ELIXIR_OF_POISON_RES = 3386
 LFGListEntryCreation_GetAutoCreateData = <function> defined @FrameXML\LFGList.lua:1102
 LAG_TOLERANCE = "Lag Tolerance"
 SendStationeryBackgroundRight = SendStationeryBackgroundRight {
 }
 PetStableStabledPet7 = PetStableStabledPet7 {
 }
 TUTORIAL61_SPELLID_DRUID = "768"
 CONQUEST_BAR = "Conquest %d / %d"
 MultiBarLeftButton9Border = MultiBarLeftButton9Border {
 }
 LE_GAME_ERR_NOT_ON_TOURNAMENT_REALM = 855
 BT4Button13

### Steps To Reproduce

Happens when logging into the game

**Comment by Gethe** [comment]
Thanks for the reports, but next time please make separate issues for substantially different errors.
