### ISSUE TITLE
[Bug] TBC Error on Login

### ISSUE THREAD

**Issue by Jeremy7600** [Gethe/Aurora#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

TBC Classic

### Current Behavior

Message: Interface\AddOns\Aurora\aurora.lua:124: hooksecurefunc(): CharacterFrame is not a function
Time: Sun Jun  5 10:30:42 2022
Count: 1
Stack: Interface\AddOns\Aurora\aurora.lua:124: hooksecurefunc(): CharacterFrame is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface\AddOns\Aurora\aurora.lua"]:124: in function `OnLoad'
[string "@Interface\AddOns\Aurora\Skin\init.lua"]:237: in function <Interface\AddOns\Aurora\Skin\init.lua:231>

Locals: 

### Expected Behavior

No errors, frames skinned

### Steps To Reproduce

1. Log in to game
2. error occurs

### Additional context

No other addons loaded or not.

**Comment by Gethe** [comment]
did you get any other errors? If not, try running `/reload` after logging in.

**Comment by Jeremy7600** [comment]
I had some other code going on in there, i have removed that and now it works.
