### ISSUE TITLE
[Bug]ReputationFrame.lua:19\21,  attempt to call method 'SetBackdrop' (a nil value)

### ISSUE THREAD

**Issue by CrisReus** [Gethe/Aurora#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

4x ...s\Aurora\Skin\FrameXML\ReputationFrame.lua:19: attempt to call method 'SetBackdrop' (a nil value)
[string "@Aurora\Skin\FrameXML\ReputationFrame.lua"]:19: in function <...s\Aurora\Skin\FrameXML\ReputationFrame.lua:17>
[string "=[C]"]: in function `ReputationFrame_SetRowType'
[string "Error in: Character Sheet':'initialization"]:488: in function `ReputationFrame_Update'
[string "Error in: Character Sheet':'initialization"]:661: in function <[string "Error in: Character Sheet':'initialization"]:598>
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:3017: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2862: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2730: in function <FrameXML\UIParent.lua:2726>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3582: in function <FrameXML\UIParent.lua:3561>
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML\CharacterFrame.lua"]:21: in function `ToggleCharacter'
[string "TOGGLECHARACTER0"]:1: in function <[string "TOGGLECHARACTER0"]:1>

Locals:
factionRow = ReputationBar21 {
 0 = <userdata>
 index = 21
 isCollapsed = false
 hasRep = false
 rolloverText = "|cffffffff 0 / 3,000|r"
 standingText = "中立"
}
isChild = false
isHeader = true
hasRep = false
(*temporary) = nil
(*temporary) = ReputationBar21 {
 0 = <userdata>
 index = 21
 isCollapsed = false
 hasRep = false
 rolloverText = "|cffffffff 0 / 3,000|r"
 standingText = "中立"
}
(*temporary) = false
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"

32x ...s\Aurora\Skin\FrameXML\ReputationFrame.lua:21: attempt to call method 'SetBackdrop' (a nil value)
[string "@Aurora\Skin\FrameXML\ReputationFrame.lua"]:21: in function <...s\Aurora\Skin\FrameXML\ReputationFrame.lua:17>
[string "=[C]"]: in function `ReputationFrame_SetRowType'
[string "Error in: Character Sheet':'initialization"]:488: in function `ReputationFrame_Update'
[string "Error in: Character Sheet':'initialization"]:661: in function <[string "Error in: Character Sheet':'initialization"]:598>
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:3017: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2862: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2730: in function <FrameXML\UIParent.lua:2726>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3582: in function <FrameXML\UIParent.lua:3561>
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML\CharacterFrame.lua"]:21: in function `ToggleCharacter'
[string "TOGGLECHARACTER0"]:1: in function <[string "TOGGLECHARACTER0"]:1>

Locals:
factionRow = ReputationBar16 {
 0 = <userdata>
 index = 16
 isCollapsed = false
 hasRep = true
 standingText = "崇拜"
}
isChild = false
isHeader = false
hasRep = false
(*temporary) = nil
(*temporary) = ReputationBar16 {
 0 = <userdata>
 index = 16
 isCollapsed = false
 hasRep = true
 standingText = "崇拜"
}
(*temporary) = true
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"

**Comment by Gethe** [comment]
Are you still getting this error? I haven't been able to reproduce it.

**Comment by CrisReus** [comment]
This error will not occur again
