### ISSUE TITLE
[Bug] Wotlk Nothng Skinned

### ISSUE THREAD

**Issue by Epidemedabear** [Gethe/Aurora#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Wotlk Classic

### Current Behavior

The following error occurs using the latest beta version released for Wotlk Classic and the addon fails to do anything.

`3x Aurora\aurora-9.2.7.0.lua:139: hooksecurefunc(): FriendsFrame is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Aurora\aurora-9.2.7.0.lua"]:139: in function `OnLoad'
[string "@Aurora\Skin\init.lua"]:244: in function <Aurora\Skin\init.lua:238>

Locals:
`

**Comment by Gethe** [comment]
Fixed with b0f9de3
