### ISSUE TITLE
[Bug]When opening profession window

### ISSUE THREAD

**Issue by Epidemedabear** [Gethe/Aurora#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Wotlk Classic

### Current Behavior

 When opening Alchemy profession window I get the following error

`2x ...kin\Interface_WrathBlizzard_TradeSkillUI.lua:27: attempt to index field '_minus' (a nil value)
[string "@Aurora\Skin\Interface_WrathBlizzard_TradeSkillUI.lua"]:27: in function <...kin\Interface_WrathBlizzard_TradeSkillUI.lua:15>
[string "=[C]"]: in function `TradeSkillFrame_Update'
[string "@Interface_WrathBlizzard_TradeSkillUI\Blizzard_TradeSkillUI.lua"]:71: in function <...dOns\Blizzard_TradeSkillUI\Blizzard_TradeSkillUI.lua:57>
[string "=[C]"]: in function `TradeSkillOnlyShowMakeable'
[string "@Interface_WrathBlizzard_TradeSkillUI\Blizzard_TradeSkillUI.lua"]:39: in function `TradeSkillFrame_OnShow'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[string "=[C]"]: in function `Show'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2214: in function `SetUIPanel'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2059: in function `ShowUIPanel'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:1927: in function <Interface_Wrath\FrameXML\UIParent.lua:1923>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2718: in function `ShowUIPanel'
...
[string "@TradeSkillMaster\LibTSM\Util\Event.lua"]:101: in function <TradeSkillMaster\LibTSM\Util\Event.lua:93>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseAction'
[string "@FrameXML\SecureTemplates.lua"]:343: in function `handler'
[string "@FrameXML\SecureTemplates.lua"]:625: in function <FrameXML\SecureTemplates.lua:569>
[string "=[C]"]: ?
[string "@FrameXML\SecureHandlers.lua"]:266: in function <FrameXML\SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@FrameXML\SecureHandlers.lua"]:296: in function <FrameXML\SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals:
id = nil
hasScroll = true
updateBackdrops = true
(for index) = 9
(for limit) = 27
(for step) = 1
i = 9
skillButton = TradeSkillSkill9 {
 0 = <userdata>
 isHighlighted = false
 r = 0.500000
 text = TradeSkillSkill9Text {
 }
 g = 0.500000
 b = 0.500000
}
_ = "Elixir of Major Firepower"
skillType = "trivial"
(*temporary) = nil
(*temporary) = nil
(*temporary) = 0
(*temporary) = nil
(*temporary) = "attempt to index field '_minus' (a nil value)"
hadScroll = false
`

**Comment by Gethe** [comment]
Do you still get this with just Aurora enabled? I haven't been able to replicate this.

**Comment by Epidemedabear** [comment]
Hi sorry I should have tested that myself in the first place, no with just Aurora installed its fine so I guess its an interaction with TSM when tradeskill windows are opened that causes the error.

**Comment by arnvid** [comment]
Closing this for now - am working on redoing the Classic/SOD/etc implementation. But for now I have disabled the packaging of these modules and closing the tickets related to this. Sorry I cannot update anymore at this time.  The wow-ui-sources are getting more in-line to make this a reality and thus why I am working on a restructure of all of these things.
