### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by nzcool** [Gethe/Aurora#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Classic Era

### Current Behavior

1x [string "TradeListScrollFrame:OnLoad"]:3: attempt to call method 'SetBackdrop' (a nil value)
[string "*:OnLoad"]:3: in function <[string "*:OnLoad"]:1>

Locals:
self = TradeListScrollFrame {
 ScrollBar = TradeListScrollFrameScrollBar {
 }
 offset = 0
 ScrollChildFrame = TradeListScrollFrameScrollChildFrame {
 }
 0 = <userdata>
}
scrollBar = TradeListScrollFrameScrollBar {
 0 = <userdata>
 ThumbTexture = TradeListScrollFrameScrollBarThumbTexture {
 }
 ScrollUpButton = TradeListScrollFrameScrollBarScrollUpButton {
 }
 ScrollDownButton = TradeListScrollFrameScrollBarScrollDownButton {
 }
}
(*temporary) = nil
(*temporary) = TradeListScrollFrameScrollBar {
 0 = <userdata>
 ThumbTexture = TradeListScrollFrameScrollBarThumbTexture {
 }
 ScrollUpButton = TradeListScrollFrameScrollBarScrollUpButton {
 }
 ScrollDownButton = TradeListScrollFrameScrollBarScrollDownButton {
 }
}
(*temporary) = <table> {
 bgFile = "ChatFrame\ChatFrameBackground"
 tileSize = 16
 tile = true
 edgeFile = "TheBurningTrade\ScrollTrack"
 edgeSize = 16
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"

**Comment by Gethe** [comment]
What are you doing when you get this error?
Do you still get it with only Aurora enabled?

**Comment by Gethe** [comment]
Closing this due to lack of response and lack of reproducibility.
