### ISSUE TITLE
[Bug] Character, Guild, Collection Windows, Bags and Chat have the old Blizz UI after updating Aurora 10.0 game ver.

### ISSUE THREAD

**Issue by msyanig** [Gethe/Aurora#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

![image](https://user-images.githubusercontent.com/43123100/197990975-ea8d3dfc-9ccd-46b4-9481-6fb42df3da65.png)

Aurora isn't working on retail after updating it to 10.0 Game Ver.

NOT WORKING:
- Character window
- Collections window
- Guild & Communities window
- Chat
- Bag

I also attached the screenshot for proof.

I hope this will get fixed. I choose Aurora than the default Blizz frames. Thanks in advance, devs!

**Comment by aers** [comment]
> Adding to this. I experience the same. 297 lua errors when I log into the game world.
> 
> Each error starts "attempt to call field 'some field name' (a nil value).
> 
> I have tried using the latest and previous builds and clearing Aurora from SavedVariables, with same result.
> 
> Attached is the first of them. [lua error.txt](https://github.com/Gethe/Aurora/files/9869371/lua.error.txt)

This is caused by the addon loading init.lua before LibStub. You can fix it by moving libs\Libs.xml before Skin\skin.xml in the .toc.

**Comment by msyanig** [comment]
> 

![image](https://user-images.githubusercontent.com/43123100/198122964-c39d3054-60d5-47a9-915e-f08e9b32d9da.png)

Thank you! I moved the texts in the .toc file and it is now working! :)

**Comment by mlablah** [comment]
> This is caused by the addon loading init.lua before LibStub. You can fix it by moving libs\Libs.xml before Skin\skin.xml in the .toc.

Awesome. Moving that line fixed most of the errors for me. I no longer get any lua errors when logging in and most interface panels appear skinned. However I noticed a few panels still triggering lua errors.

[Opening Guild & Communities](https://github.com/Gethe/Aurora/files/9874314/lua.error.-.guild.communities.txt)
[lInspecting another player](https://github.com/Gethe/Aurora/files/9874315/lua.error.-.inspect.txt)
[Opening the Collections menu](https://github.com/Gethe/Aurora/files/9874316/lua.error.-.collections.txt)
