### ISSUE TITLE
[Bug] 2 reproducible LUA Errors and 2 visual bugs

### ISSUE THREAD

**Issue by Sonnyger** [Gethe/Aurora#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

**2 LUA Errors found:**

- 100% reproducible LUA Error when opening Adventure Guide (Blizzard_EncounterJournal.lua)
- 100% reproducible LUA Error when tracking a quest which has a progress bar Kaliel's Tracker (Blizzard_ObjectiveTracker.lua)

**2 visual bugs:**

- Postal + Aurora (this one exists since like forever)
<img width="388" alt="Bildschirmfoto 2022-11-04 um 20 22 20" src="https://user-images.githubusercontent.com/116546436/200059153-19f2ac4a-be00-4d51-a758-c5b2f6c3018d.png">

- Sanctum Reservoir (background missing)
<img width="1045" alt="Bildschirmfoto 2022-11-04 um 20 23 24" src="https://user-images.githubusercontent.com/116546436/200059174-e46a6506-5210-4adf-a4c6-ade4109acc35.png">

**Comment by Sonnyger** [comment]
Another LUA Error:

- 100% reproducible LUA Error when opening the Collections Panel for the first(!) time (Blizzard_Collections.lua)

**Comment by Gethe** [comment]
Please keep different bugs in separate issues. Listing everything in one issue makes it more difficult to keep track of.

**Comment by Sonnyger** [comment]
Well did you notice/fix them all or do i need to reopen a ticket for every issue now?

**Comment by Gethe** [comment]
They have not all been fixed, please open new tickets for them.

**Comment by Sonnyger** [comment]
No, thanks. They are all listed here. I won't open new tickets and repeat myself.
