### ISSUE TITLE
[Bug] EncounterJournal.lua not fixed

### ISSUE THREAD

**Issue by Sonnyger** [Gethe/Aurora#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

23x ...etail/Interface/AddOns/Blizzard_EncounterJournal.lua:82: attempt to index field 'lootScroll' (a nil value)
[string "@Interface/AddOns/Aurora/Skin/Retail/Interface/AddOns/Blizzard_EncounterJournal.lua"]:82: in function <...etail/Interface/AddOns/Blizzard_EncounterJournal.lua:77>
[string "=[C]"]: in function `EncounterJournal_UpdateFilterString'
[string "@Interface/AddOns/Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua"]:1976: in function `EncounterJournal_LootUpdate'
[string "@Interface/AddOns/Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua"]:539: in function <...zzard_EncounterJournal/Blizzard_EncounterJournal.lua:529>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/UIParent.lua"]:2844: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2687: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2552: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3150: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:3111: in function `ToggleFrame'
[string "@Interface/FrameXML/UIParent.lua"]:1115: in function `ToggleEncounterJournal'
[string "@Interface/FrameXML/MainMenuBarMicroButtons.lua"]:1140: in function <Interface/FrameXML/MainMenuBarMicroButtons.lua:1138>
[string "=[C]"]: ?

Locals:
classID = 11
classInfo = <table> {
 classID = 11
 classFile = "DRUID"
 className = "Druid"
}
(*temporary) = nil
(*temporary) = 11
(*temporary) = <table> {
 classID = 11
 classFile = "DRUID"
 className = "Druid"
}
(*temporary) = 11
(*temporary) = nil
(*temporary) = "attempt to index field 'lootScroll' (a nil value)"

### Expected Behavior

Expected to be fixed with latest update.
Not fixed.

### Steps To Reproduce

open adventure guide

**Comment by Gethe** [comment]
Some of the more recent updates were done on beta, so you may need to wait for 10.0.2
