### ISSUE TITLE
[Bug] LootHistory.lua

### ISSUE THREAD

**Issue by CrisReus** [Gethe/Aurora#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

43x ...ddOns/Aurora/Skin/FrameXML/LootHistory.lua:25: attempt to call field 'CropIcon' (a nil value)
[string "@Aurora/Skin/FrameXML/LootHistory.lua"]:25: in function <...ddOns/Aurora/Skin/FrameXML/LootHistory.lua:13>
[string "=[C]"]: ?
[string "=[C]"]: in function `LootHistoryFrame_UpdateItemFrame'
[string "@FrameXML/LootHistory.lua"]:68: in function `LootHistoryFrame_FullUpdate'
[string "@FrameXML/LootHistory.lua"]:28: in function <FrameXML/LootHistory.lua:26>

Locals:
self = LootHistoryFrame {
 0 = <userdata>
 unusedPlayerFrames = <table> {
 }
 Divider = Texture {
 }
 Label = FontString {
 }
 usedPlayerFrames = <table> {
 }
 layoutType = "TooltipDefaultLayout"
 GetBackdropColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:191
 highlightedRolls = <table> {
 }
 ResizeButton = Button {
 }
 expandedRolls = <table> {
 }
 ScrollFrame = LootHistoryFrameScrollFrame {
 }
 NineSlice = Frame {
 }
 TooltipBackdropOnLoad = <function> defined @SharedXML/SharedTooltipTemplates.lua:172
 itemFrames = <table> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:199
 SetBorderBlendMode = <function> defined @SharedXML/SharedTooltipTemplates.lua:203
 SetBackdropBorderColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:195
 DragButton = Button {
 }
 SetBackdropColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:187
 CloseButton = Button {
 }
 LootIcon = Texture {
 }
}
frame = Button {
 0 = <userdata>
 ItemName = FontString {
 }
 Divider = Texture {
 }
 itemIdx = 1
 NameBorderRight = Texture {
 }
 itemLink = "|cffa335ee|Hitem:188254::::::::60:104::90:4:8763:6652:1511:6646::::::|h[嚴酷星蝕]|h|r"
 NameBorderMid = Texture {
 }
 rollID = 26
 ActiveHighlight = Texture {
 }
 ToggleButton = Button {
 }
 WinnerName = FontString {
 }
 IconBorder = Texture {
 }
 WinnerRollType = Texture {
 }
 WinnerRoll = FontString {
 }
 Icon = Texture {
 }
 NameBorderLeft = Texture {
 }
}
rollID = 26
_ = "|cffa335ee|Hitem:188254::::::::60:104::90:4:8763:6652:1511:6646::::::|h[嚴酷星蝕]|h|r"
_ = 25
isDone = false
winnerIdx = nil
expanded = nil
(*temporary) = nil
(*temporary) = Texture {
 0 = <userdata>
}
(*temporary) = Button {
 0 = <userdata>
 ItemName = FontString {
 }
 Divider = Texture {
 }
 itemIdx = 1
 NameBorderRight = Texture {
 }
 itemLink = "|cffa335ee|Hitem:188254::::::::60:104::90:4:8763:6652:1511:6646::::::|h[嚴酷星蝕]|h|r"
 NameBorderMid = Texture {
 }
 rollID = 26
 ActiveHighlight = Texture {
 }
 ToggleButton = Button {
 }
 WinnerName = FontString {
 }
 IconBorder = Texture {
 }
 WinnerRollType = Texture {
 }
 WinnerRoll = FontString {
 }
 Icon = Texture {
 }
 NameBorderLeft = Texture {
 }
}
(*temporary) = "attempt to call field 'CropIcon' (a nil value)"
Skin = <table> {
 AchievementHeaderStatusBarTemplate = <function> defined @Aurora/SkinBlizzard_AchievementUI.lua:173
 LFGSpecificChoiceTemplate = <function> defined @Aurora/Skin/FrameXML/LFGFrame.lua:125
 GuildChallengeAlertFrameTemplate = <function> defined @Aurora/Skin/FrameXML/AlertFrameSystems.lua:219
 PopupButtonTemplate = <function> defined @Aurora/Skin/FrameXML/ItemButtonTemplate.lua:271
 PetBattleUnitTooltipAuraTemplate = <function> defined @Aurora/SkinBlizzard_PetBattleUI.lua:86
 AuctionHouseAuctionsFrameTemplate = <function> defined @Aurora/SkinBlizzard_AuctionHouseUI.lua:397
 AuctionHouseItemDisplayBaseTemplate = <function> defined @Aurora/SkinBlizzard_AuctionHouseUI.lua:170
 AchievementAlertFrameTemplate = <function> defined @Aurora/Skin/FrameXML/AlertFrameSystems.lua:121
 UnitPopupVoiceToggleButtonTemplate = <function> defined @Aurora/Skin/FrameXML/UnitPopupCustomControls.lua:15
 InputBoxInstructionsTemplate = <function> defined @Aurora/Skin/SharedXML/SharedUIPanelTemplates.lua:679
 ComparisonPlayerTemplate = <function> defined @Aurora/SkinBlizzard_AchievementUI.lua:252
 OptionsListButtonTemplate = <function> defined @Aurora/Skin/SharedXML/DeprecatedTemplates.lua:49
 MoneyInputFrameTemplate = <function> defined @Aurora/Skin/FrameXML/MoneyInputFrame.lua:16
 HybridScrollBarTemplate = <function> defined @Aurora/S

**Comment by Gethe** [comment]
Please keep issues separate
