### ISSUE TITLE
[Bug]SkinBlizzard_EncounterJournal.lua:82: attempt to index field 'lootScroll' (a nil value)

### ISSUE THREAD

**Issue by CrisReus** [Gethe/Aurora#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

11x .../SkinBlizzard_EncounterJournal.lua:82: attempt to index field 'lootScroll' (a nil value)
[string "@Aurora/SkinBlizzard_EncounterJournal.lua"]:82: in function <.../SkinBlizzard_EncounterJournal.lua:77>
[string "=[C]"]: in function `EncounterJournal_UpdateFilterString'
[string "@Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua"]:2010: in function `EncounterJournal_LootUpdate'
[string "@Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua"]:557: in function <...zzard_EncounterJournal/Blizzard_EncounterJournal.lua:547>
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:2853: in function `SetUIPanel'
[string "@FrameXML/UIParent.lua"]:2696: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:2561: in function <FrameXML/UIParent.lua:2557>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3159: in function <FrameXML/UIParent.lua:3138>
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:3120: in function `ToggleFrame'
[string "@FrameXML/UIParent.lua"]:1117: in function `ToggleEncounterJournal'
[string "@FrameXML/MainMenuBarMicroButtons.lua"]:1140: in function <FrameXML/MainMenuBarMicroButtons.lua:1138>
[string "=[C]"]: ?

Locals:
classID = 11
classInfo = <table> {
 classID = 11
 classFile = "DRUID"
 className = "德魯伊"
}
(*temporary) = nil
(*temporary) = 11
(*temporary) = <table> {
 classID = 11
 classFile = "DRUID"
 className = "德魯伊"
}
(*temporary) = 11
(*temporary) = nil
(*temporary) = "attempt to index field 'lootScroll' (a nil value)"

**Comment by devil81** [comment]
same for LFG : 

12x ...ceAurora/Skin/FrameXML/LFGList.lua:132: attempt to call field 'GetActivityInfo' (a nil value)
[string "@Aurora/Skin/FrameXML/LFGList.lua"]:132: in function <...ceAurora/Skin/FrameXML/LFGList.lua:130>
[string "=[C]"]: ?
[string "=[C]"]: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@FrameXML/LFGList.lua"]:2596: in function <FrameXML/LFGList.lua:2593>

Locals:
tooltip = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestPartyProgress = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:303
 shouldRefreshData = false
 SetPvpTalent = <function> defined =[C]:-1
 SetRuneforgeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetHyperlink = <function> defined =[C]:-1
 SetUnit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAzeriteEssence = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 waitingForData = false
 SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
