### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by real-proof** [Gethe/Aurora#72]
I downloaded the addon and it worked properly. 
I then downloaded https://wowinterface.com/downloads/fileinfo.php?id=25941 and it worked properly. 
I logged out and back in and now the background of all the screens are grey, dungeon finder/character panel etc
![image](https://user-images.githubusercontent.com/54126464/204117377-5cba0dab-8dee-47a8-9fec-4b7ccbe66b4b.png)
i have uninstalled and reinstalled the addon and deleted and repasted the elv ui texture pack and nothing works to get the addon to work properly. 
any suggestions to get either both to work together or at least the addon to work again.

**Comment by Gethe** [comment]
I installed that texture pack, but i'm not getting that issue. Check the backdrop opacity in Aurora's settings.

**Comment by Gethe** [comment]
Closing this due to lack of response.
