### ISSUE TITLE
[BUG] Quest log not showing dark  background

### ISSUE THREAD

**Issue by johndolotko** [Gethe/Aurora#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

When opening the quest log the right hand window is not showingf the dark background thus making the text hard to read.

### Expected Behavior

The quest log windows should both be coloured dark

### Steps To Reproduce

All the time as shown in  the attached file.

![Screenshot 2022-12-14 172207](https://user-images.githubusercontent.com/49884783/207664792-5d6a3713-c489-4e9f-ae3d-93d2cf281538.jpg)

**Comment by Gethe** [comment]
This is not the stock quest log, and thus is not currently supported.

**Comment by johndolotko** [comment]
Ah ok,

But it did work previously in the last couple weeks.

Thanks for your reply pal 

Best Regards

John
