### ISSUE TITLE
[Bug]Aurora/Skin/skin.lua:150: calling 'GetStatusBarTexture' on bad self

### ISSUE THREAD

**Issue by CrisReus** [Gethe/Aurora#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

28x Aurora/Skin/skin.lua:150: calling 'GetStatusBarTexture' on bad self (Usage: local texture = self:GetStatusBarTexture())
[string "=[C]"]: in function `GetStatusBarTexture'
[string "@Aurora/Skin/skin.lua"]:150: in function <Aurora/Skin/skin.lua:149>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetStatusBarColor'
[string "@Blizzard_UIWidgets/Blizzard_UIWidgetTemplateStatusBar.lua"]:71: in function `Setup'
[string "@Blizzard_UIWidgets/Blizzard_UIWidgetManager.lua"]:459: in function `ProcessWidget'
[string "@Blizzard_UIWidgets/Blizzard_UIWidgetManager.lua"]:52: in function <...dOns/Blizzard_UIWidgets/Blizzard_UIWidgetManager.lua:46>

Locals:
(*temporary) = StatusBar {
 0 = <userdata>
 OnLeave = <function> defined @Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua:625
 OnBackdropLoaded = <function> defined @Aurora/Skin/backdrop.lua:175
 tooltipLoc = 0
 GetBackdropColor = <function> defined @Aurora/Skin/backdrop.lua:285
 SetBackdropOptions = <function> defined @Aurora/Skin/backdrop.lua:364
 barText = "0%"
 GlowLeft = Texture {
 }
 tooltip = "貢獻原料或備妥的餐點，讓每個人都能享用大餐！"
 BackgroundGlow = Texture {
 }
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 Setup = <function> defined @Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua:538
 partitionPool = <table> {
 }
 SetBackdropGradient = <function> defined @Aurora/Skin/backdrop.lua:311
 range = 10
 barMax = 10
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 GlowRight = Texture {
 }
 tooltipAnchor = "ANCHOR_BOTTOMLEFT"
 BGRight = Texture {
 }
 OnLoad = <function> defined @Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua:9
 BorderLeft = Texture {
 }
 barTextHasStyleSettings = 4
 SetTooltip = <function> defined @Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua:23
 tooltipXOffset = 0
 BorderRight = Texture {
 }
 SetMouse = <function> defined @Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua:649
 barMin = 0
 DisplayBarValue = <function> defined @Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua:580
 GlowCenter = Texture {
 }
 BGLeft = Texture {
 }
 tooltipYOffset = 0
 value = 0
 SetBackdropBorderColor = <function> defined @Aurora/Skin/backdrop.lua:289
 barValueTextType = 1
 GetBackdropTexture = <function> defined @Aurora/Skin/backdrop.lua:333
 Spark = Texture {
 }
 SparkMask = MaskTexture {
 }
 ApplyBackdrop = <function> defined @Aurora/Skin/backdrop.lua:193
 SetBackdrop = <function> defined @Aurora/Skin/backdrop.lua:246
 UpdateLabel = <function> defined @Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua:630
 SetTooltipOwner = <function> defined @Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua:53
 GetBackdropBorderColor = <function> defined @Aurora/Skin/backdrop.lua:305
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 UpdateMouseEnabled = <function> defined @Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua:12
 overrideBarText = ""
 tooltipContainsHyperLink = false
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 Label = FontString {
 }
 SetBackdropOption = <function> defined @Aurora/Skin/backdrop.lua:342
 barTextSizeType = 4
 barTextFontType = 1
 SetBackdropLayer = <function> defined @Aurora/Skin/backdrop.lua:319
 barTextEnabledState = 3
 displayedValue = 0
 UpdateBar = <function> defined @Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua:568
 overrideBarTextShownType = 0
 SetStatusBarColor = <function> defined =[C]:-1
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 OnEnter = <function> defined @Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua:620
 __SetStatusBarTexture = true
 SetStatusBarTexture = <function> defined =[C]:-1
 backdropInfo = <table> {
 }
 _backdropInfo = <table> {
 }
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 defaultTooltipAnchor = "ANCHOR_BOTTOMLEFT"
 SetBarText = <function> defined @Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua:591
 OnReset = <function> defined @Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua:697
 UpdatePartitions = <function> defined @Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua:689
 SetBackdropColor = <function> def

**Comment by Gethe** [comment]
Have you gotten this again recently? If so, what were you doing?
