### ISSUE TITLE
[Bug] Aurora causes Stuf addon to not even load

### ISSUE THREAD

**Issue by socalminstrel** [Gethe/Aurora#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

Stuf (a long-standing unit frames addon) was recently [fan-updated for Dragonflight](https://drive.google.com/u/0/uc?id=10fUrChU3berMivvKdMBbI-6d4mUb3LO7&export=download), and works perfectly--except when Aurora is enabled. Then the effects of the addon don't show up and the addon doesn't even show up in the in-game addon configuration section (Options->Addons tab) like it normally would.

I realize that this is a fairly niche thing and you may not have the time/interest to make it work with this one addon, but it's such a surprising behavior and I love both addons, so I thought I'd mention it.

### Expected Behavior

That Stuf would continue to operate as normal with Aurora enabled.

### Steps To Reproduce

Install Stuf and enable it.
Install Aurora and enable it.
Open the WoW Options menu, click the Addons tab
Stuf is no longer listed there, nor are unit frames effected by Stuf

### Additional context

This behavior has been happening since the beginning of Dragonflight, not just with the latest patch.

**Comment by Gethe** [comment]
Aurora isn't set up to allow it to remove entries from the AddOn List. Can you verify that Stuf is (or not) listed in the addons list when you're at the character select screen?

**Comment by socalminstrel** [comment]
It's listed in the addons list on the character selection screen and checked off as enabled. In game, if I enable Aurora and reload, the Stuf unit frames disappear (the default ones are there instead) and in Options->Addons, Stuf is no longer listed there (whereas it was before the reload). If I disable Aurora and reload, the Stuf unit frames are back and it's again in the Options->Addons tab.

I didn't mean to use technical terms in terms of loading, I don't know what's happening to Stuf under the hood. I just meant that it's not that Stuf simply isn't working--it's not even listed in the Options->Addons tab, as though it's disabled even though it's not.

**Comment by Squatty1** [comment]
I tried installing stuf from the link you provided, with aurora. I had no issues.

**Comment by socalminstrel** [comment]
Hmm, strange. I tried disabling all addons except for Stuf and Aurora, to make sure it wasn't some additional addon interaction, and Stuf still doesn't show up. 

To be totally clear, I only use the Stuf Unit Frames, Stuf_Options and Stuf_Range modules...I don't enable Stuf Raid Frames and Stuf Raid Options generally. I tried enabling those too, in case somehow that changed things. It seems Stuf Raid still works with Aurora, but Stuf Unit Frames, the part I use, doesn't. And now I realize that since Stuf_Options is a module (or, an addon you have to enable) it not working is why Stuf doesn't even show up in the Options->Addons tab.

**Comment by Squatty1** [comment]
I don't know what to tell you, it worked for me and I have a lot of other addons as well. I did notice that Stuf showed up twice in my addon panel, perhaps the fan update is not without issues.
