### ISSUE TITLE
[Bug] Missing textures and role checks in premade groups. 

### ISSUE THREAD

**Issue by Linktotherescue** [Gethe/Aurora#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

Missing images after 10.0.5 update in group finder for class type (Damage, Tank, Healer)

Lots of other textures and windows are not like before.  = (z
![WoW Aurora](https://user-images.githubusercontent.com/123845341/215296807-96e3d57d-28fc-4e28-b02c-df2063fe8f11.JPG)

### Expected Behavior

Old textures and showing of class icons. 

### Steps To Reproduce

Open premade groups in dungeon finder.

**Comment by vojtasrb** [comment]
Yep, same thing I opened issue about few days ago. No answer. Author just doesn't care anymore I guess.

**Comment by Linktotherescue** [comment]
I am assuming they are just busy with real life stuff. They have taken the time to update during each patch! Hopefully they are continuing the project. We appreciate everything that they are doing to maintain the addon so we don't have to look at the ugly default wow stuff.

**Comment by vojtasrb** [comment]
At least an update, if it's being worked on, would be nice though.

**Comment by Jeremy7600** [comment]
The typical timeframe is about 2 to 3 weeks after a major API change for updates to Aurora in the past. Could be less, could be more. Commits were made in the last day or two, so work is being done.

**Comment by Linktotherescue** [comment]
Awesome! Thanks so much for the update! I didn't realize how much I love this addon until I disabled it and was like "WoW is ugly" lol.

**Comment by Jeremy7600** [comment]
Just providing info based on the last 2 or 3 API changes; I'm in the same boat as you.

**Comment by Linktotherescue** [comment]
@Jeremy7600 @vojtasrb There has been a new Beta update that seems to fix most of the issues.
