### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Nabohs** [Gethe/Aurora#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Wrath Classic

### Current Behavior

Bug Issues w/ RCLC (RC Loot Council)

### Expected Behavior

Zero LUA Issues

### Steps To Reproduce

Enable Aurora with RCLC and no other addons

### Additional context

189x .../Skin/SharedXML/SharedUIPanelTemplates.lua:565: attempt to index local 'Frame' (a nil value)
[string "@Aurora/Skin/SharedXML/SharedUIPanelTemplates.lua"]:565: in function `NineSlicePanelTemplate'
[string "@Aurora/Skin/SharedXML/SharedTooltipTemplates.lua"]:32: in function `TooltipBackdropTemplate'
[string "@RCLootCouncil_Classic/RCLootCouncil/Libs/MSA-DropDownMenu-1.0/MSA-DropDownMenu-1.0.lua"]:1704: in function <...l/Libs/MSA-DropDownMenu-1.0/MSA-DropDownMenu-1.0.lua:1700>
[string "@RCLootCouncil_Classic/RCLootCouncil/Libs/MSA-DropDownMenu-1.0/MSA-DropDownMenu-1.0.lua"]:1714: in function <...l/Libs/MSA-DropDownMenu-1.0/MSA-DropDownMenu-1.0.lua:1711>

Locals:
Frame = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'Frame' (a nil value)"
Hook = <table> {
 MerchantFrame_UpdateCurrencies = <function> defined @Aurora/Skin/Interface_TBC/FrameXML/MerchantFrame.lua:19
 QuestInfo_GetRewardButton = <function> defined @Aurora/Skin/Interface_Wrath/FrameXML/QuestInfo.lua:67
 MovieFrameCloseDialog_OnShow = <function> defined @Aurora/Skin/FrameXML/MovieFrame.lua:12
 BonusRollFrame_OnShow = <function> defined @Aurora/Skin/FrameXML/LootFrame.lua:83
 ChatBubble_SetName = <function> defined @Aurora/Skin/FrameXML/ChatBubbleTemplates.lua:40
 QuestFrameProgressItems_Update = <function> defined @Aurora/Skin/Interface_Wrath/FrameXML/QuestFrame.lua:13
 SetItemButtonQuality = <function> defined @Aurora/Skin/FrameXML/ItemButtonTemplate.lua:14
 CraftFrame_Update = <function> defined @Aurora/Skin/Interface_WrathBlizzard_CraftUI.lua:15
 SpellBookFrame_UpdateSkillLineTabs = <function> defined @Aurora/Skin/FrameXML/SpellBookFrame.lua:29
 AudioOptionsVoicePanel_InitializeCommunicationModeUI = <function> defined @Aurora/Skin/FrameXML/AudioOptionsPanels.lua:13
 PaperDollFrame_SetLevel = <function> defined @Aurora/Skin/Interface_Wrath/FrameXML/PaperDollFrame.lua:13
 AuctionFrameBrowse_Update = <function> defined @Aurora/Skin/Interface_WrathBlizzard_AuctionUI.lua:44
 ChannelButtonHeaderMixin = <table> {
 }
 ClassTrainer_SetToClassTrainer = <function> defined @Aurora/SkinBlizzard_TrainerUI.lua:65
 UpdateMicroButtons = <function> defined @Aurora/Skin/Interface_Wrath/FrameXML/MainMenuBarMicroButtons.lua:63
 UIDropDownMenu_SetWidth = <function> defined @Aurora/Skin/FrameXML/UIDropDownMenu.lua:116
 ClassTrainer_SetToTradeSkillTrainer = <function> defined @Aurora/SkinBlizzard_TrainerUI.lua:60
 EmbeddedItemTooltip_PrepareForSpell = <function> defined @Aurora/Skin/FrameXML/GameTooltip.lua:24
 ClassTrainer_SetSelection = <function> defined @Aurora/SkinBlizzard_TrainerUI.lua:51
 NavBar_CheckLength = <function> defined @Aurora/Skin/FrameXML/NavigationBar.lua:17
 ContainerFrameFilterIcon_SetAtlas = <function> defined @Aurora/Skin/FrameXML/ContainerFrame.lua:19
 ClassTrainerFrame_Update = <function> defined @Aurora/SkinBlizzard_TrainerUI.lua:15
 TradeSkillFrame_SetSelection = <function> defined @Aurora/Skin/Interface_WrathBlizzard_TradeSkillUI.lua:51
 TradeSkillFrame_Update = <function> defined @Aurora/Skin/Interface_WrathBlizzard_TradeSkillUI.lua:15
 ReputationFrame_Update = <function> defined @Aurora/Skin/Interface_Wrath/FrameXML/ReputationFrame.lua:18
 ObjectPoolMixin = <table> {
 }
 RaidGroupFrame_Update = <function> defined @Aurora/Skin/Interface_WrathBlizzard_RaidUI.lua:14
 MacroFrame_OnShow = <function> defined @Aurora/SkinBlizzard_MacroUI.lua:14
 LFGFrameMixin = <table> {
 }
 ChatConfig_CreateCheckboxes = <function> defined @Aurora/Skin/FrameXML/ChatConfigFrame.lua:14
 PaperDollItemSlotButton_Update = <function> defined @Aurora/Skin/Interface_Wrath/FrameXML/PaperDollFrame.lua:17
 AuctionSellItemButton_OnEvent = <function> defined @Aurora/Skin/Interface_WrathBlizzard_AuctionUI.lua:80
 QuestFrame_SetTextColor = <function> defined @Aurora/Skin/Interface_Wrath/FrameXML/QuestFrame.lua:74
 QuestFrame_ShowQuestPortrait = <function> defined @Aurora/Skin/In

**Comment by Gethe** [comment]
RCLootCouncil needs to update their version of MSA-DropDownMenu
