### ISSUE TITLE
[Bug] - Leatrix Plus enhanced quest log / professions / trainers

### ISSUE THREAD

**Issue by David-c0degeek** [Gethe/Aurora#96]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Classic Era

### Current Behavior

Enabling "Enhance quest log, Enhance Professions, Enhance trainers" in the Leatrix Plus addon.

### Expected Behavior

Aurora works (or doesn't skin, but doesn't crash / show errors)

### Steps To Reproduce

Install Leatrix Plus addon
Goto settings
Interface
Tick on the Enhance Professions + Trainers + Quest log options
Reload UI

### Additional context

Aurora crashes on 

Results in an error QuestLogFrame.lua line 26:
   attempt to index field '_minus' (a nil value)

Blizzard_CraftUI.lua line 27:
   attempt to index field '_minus' (a nil value)

Blizzard_CraftUI.lua line 39:
   attempt to call method 'SetBackdropOption' (a nil value)

Blizzard_TradeSkillUI.lua line 27:
   attempt to index field '_minus' (a nil value)

Blizzard_TradeSkillUI.lua line 41:
   attempt to call method 'SetBackdropOption' (a nil value)

Would be really great if these 2 could work together (or at least not crash and burn)

**Comment by arnvid** [comment]
Closing this for now - am working on redoing the Classic/SOD/etc implementation. But for now I have disabled the packaging of these modules and closing the tickets related to this. Sorry I cannot update anymore at this time.  The wow-ui-sources are getting more in-line to make this a reality and thus why I am working on a restructure of all of these things.
