### ISSUE TITLE
[Bug]Errors on Load in WotLK, no skinning

### ISSUE THREAD

**Issue by Jeremy7600** [Gethe/Aurora#97]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Wrath Classic

### Current Behavior

Logging in I get an error about  hooksecurefunc

1x Aurora/Skin/skin.lua:61: Usage: hooksecurefunc([table,] "function", hookfunc)
[string "=[C]"]: in function `hooksecurefunc'
[string "@Aurora/Skin/skin.lua"]:61: in function <Aurora/Skin/skin.lua:60>
[string "=[C]"]: in function `FrameTypeButton'
[string "@Aurora/Skin/SharedXML/SecureUIPanelTemplates.lua"]:35: in function `UIPanelScrollBarButton'
[string "@Aurora/Skin/SharedXML/SecureUIPanelTemplates.lua"]:50: in function `UIPanelScrollUpButtonTemplate'
[string "@Aurora/Skin/SharedXML/SecureUIPanelTemplates.lua"]:69: in function `UIPanelScrollBarTemplate'
[string "@Aurora/Skin/SharedXML/SecureUIPanelTemplates.lua"]:82: in function `UIPanelScrollFrameTemplate'
[string "@Aurora/Skin/SharedXML/SharedBasicControls.lua"]:48: in function `?'
[string "@Aurora/Skin/init.lua"]:165: in function <Aurora/Skin/init.lua:149>

Locals:
(*temporary) = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @FrameXML/ActionButton.lua:70
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 SettingsSliderOptionsMixin = <table> {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 791
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 409
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this group."
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 InterfaceOptionsNamesPanelUnitNameplatesShowAll = InterfaceOptionsNamesPanelUnitNameplatesShowAll {
 }
 VideoOptionsFrameDefaults = VideoOptionsFrameDefaults {
 }
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 INSTANCE_UNAVAILABLE_OTHER_TEMPORARILY_DISABLED = "%s cannot enter. This instance is temporarily disabled."
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 IsReferAFriendLinked = <function> defined =[C]:-1
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML/UnitFrame.lua:623
 CALENDAR_RAID_RESET_DESCRIPTION = "%1$s resets at %2$s."
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 CONSOLIDATED_BUFFS_PER_ROW = 4
 MoneyFrame_OnEvent = <function> defined @FrameXML/MoneyFrame.lua:224
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 AutoCompleteEditBox_OnKeyDown = <function> defined @FrameXML/AutoComplete.lua:368
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LE_GAME_ERR_ONLY_ONE_QUIVER = 33
 SpellButton6Cooldown = SpellButton6Cooldown {
 }
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 Graphics_QualityText = Graphics_QualityText {
 }
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 ROGUE_COMBAT_CORE_ABILITY_4 = "Melee ability with an increased range that consumes Combo Points."
 JoinSkirmish = <function> defined =[C]:-1
 Advanced_GraphicsAPIDropDownButtonHighlightTexture = Advanced_GraphicsAPIDropDownButtonHighlightTexture {
 }
 MultiBarRightButton7Shine9 = MultiBarRightButton7Shine9 {
 }
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 DMG_LCD = "DMG"
 RaidGraphics_EnvironmentalDetailSlider = RaidGraphics_EnvironmentalDetailSlider {
 }
 PetPaperDollFrameTab3Right = PetPaperDollFrameTab3Right {
 }
 Is64BitClient = <function> defined =[C]:-1
 SecureCmdItemParse = <function> defined @FrameXML/ChatFrame.lua:1148
 SLASH_STOPATTACK1 = "/stopattack"
 MultiCastActionButton4HotKey = MultiCastActionButton4HotKey {
 }
 CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle = CompactRaidFrameManagerDisplayFrameFilterOptionsFilterRoleTankMiddleMiddle {
 }
 SortQuestWatches = <function> defined =[C]:-1
 ContainerFrame4Item16Cooldown = ContainerFrame4Item16Cooldown {
 }
 MINIMAP_TRACKING_TRAINER_CLASS = "Class Trainer"
 SLASH_DISMOUNT2 = "/dismount"
 DUNGEON_FLOOR_DRAGONBLIGHTCHROMIESCENARIO2 = "Andorhal"
 PlayerFrame_UpdateReadyCheck = <function> defined @FrameXML/PlayerFrame.lua:360
 EMOTE69_CMD1 = "/nosepick"
 SPELL_FAILED_CUSTOM_ERROR_152 = "You must choose a specialization to use Ascendance."
 LAG_TOLERANCE = "Lag Tolerance"
 GuildControlPopupFrame = GuildControlPopupFrame {
 }
 ARENA

### Expected Behavior

No error, windows skinned. 

### Steps To Reproduce

Log in to Wrath Classic
Error appears at logon. 

### Additional context

Does not matter if aurora loads alone or with other addons. Also occurs with Currency UI bug

**Comment by lgrano** [comment]
Having the same issue, its broken on current wotlk patch. i have tested without any other addons active.

**Comment by arnvid** [comment]
Closing this for now - am working on redoing the Classic/SOD/etc implementation. But for now I have disabled the packaging of these modules and closing the tickets related to this. Sorry I cannot update anymore at this time.  The wow-ui-sources are getting more in-line to make this a reality and thus why I am working on a restructure of all of these things.
