### ISSUE TITLE
[Bug]TokenUI Error on load and when currency tab is opened

### ISSUE THREAD

**Issue by Jeremy7600** [Gethe/Aurora#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Wrath Classic

### Current Behavior

3x ...ora/Skin/Interface_WrathBlizzard_TokenUI.lua:26: attempt to index field '_auroraMinus' (a nil value)
[string "@Aurora/Skin/Interface_WrathBlizzard_TokenUI.lua"]:26: in function <...ora/Skin/Interface_WrathBlizzard_TokenUI.lua:14>
[string "=[C]"]: in function `TokenFrame_Update'
[string "@Blizzard_TokenUI/Blizzard_TokenUI.lua"]:51: in function <Blizzard_TokenUI/Blizzard_TokenUI.lua:49>

Locals:
buttons = <table> {
 1 = TokenFrameContainerButton1 {
 }
 2 = TokenFrameContainerButton2 {
 }
 3 = TokenFrameContainerButton3 {
 }
 4 = TokenFrameContainerButton4 {
 }
 5 = TokenFrameContainerButton5 {
 }
 6 = TokenFrameContainerButton6 {
 }
 7 = TokenFrameContainerButton7 {
 }
 8 = TokenFrameContainerButton8 {
 }
 9 = TokenFrameContainerButton9 {
 }
 10 = TokenFrameContainerButton10 {
 }
 11 = TokenFrameContainerButton11 {
 }
 12 = TokenFrameContainerButton12 {
 }
 13 = TokenFrameContainerButton13 {
 }
 14 = TokenFrameContainerButton14 {
 }
 15 = TokenFrameContainerButton15 {
 }
 16 = TokenFrameContainerButton16 {
 }
 17 = TokenFrameContainerButton17 {
 }
 18 = TokenFrameContainerButton18 {
 }
 19 = TokenFrameContainerButton19 {
 }
 20 = TokenFrameContainerButton20 {
 }
 21 = TokenFrameContainerButton21 {
 }
}
(for index) = 1
(for limit) = 21
(for step) = 1
i = 1
button = TokenFrameContainerButton1 {
 0 = <userdata>
 index = 1
 stripe = TokenFrameContainerButton1Stripe {
 }
 OnBackdropLoaded = <function> defined @Aurora/Skin/backdrop.lua:175
 GetBackdropColor = <function> defined @Aurora/Skin/backdrop.lua:285
 SetBackdropOptions = <function> defined @Aurora/Skin/backdrop.lua:364
 SetBackdropBorderColor = <function> defined @Aurora/Skin/backdrop.lua:289
 isUnused = false
 GetBackdropTexture = <function> defined @Aurora/Skin/backdrop.lua:333
 isExpanded = true
 expandIcon = TokenFrameContainerButton1ExpandIcon {
 }
 SetBackdrop = <function> defined @Aurora/Skin/backdrop.lua:246
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 LinkButton = Button {
 }
 GetBackdropBorderColor = <function> defined @Aurora/Skin/backdrop.lua:305
 categoryRight = TokenFrameContainerButton1CategoryRight {
 }
 check = TokenFrameContainerButton1Check {
 }
 SetBackdropGradient = <function> defined @Aurora/Skin/backdrop.lua:311
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 highlight = TokenFrameContainerButton1Highlight {
 }
 Center = Texture {
 }
 RightEdge = Texture {
 }
 SetBackdropLayer = <function> defined @Aurora/Skin/backdrop.lua:319
 count = TokenFrameContainerButton1Count {
 }
 BottomEdge = Texture {
 }
 backdropInfo = <table> {
 }
 isHeader = true
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 BottomRightCorner = Texture {
 }
 GetBackdropOption = <function> defined @Aurora/Skin/backdrop.lua:358
 BottomLeftCorner = Texture {
 }
 isWatched = false
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 TopEdge = Texture {
 }
 _backdropInfo = <table> {
 }
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 ApplyBackdrop = <function> defined @Aurora/Skin/backdrop.lua:193
 icon = TokenFrameContainerButton1Icon {
 }
 GetBackdropLayer = <function> defined @Aurora/Skin/backdrop.lua:328
 SetBackdropOption = <function> defined @Aurora/Skin/backdrop.lua:342
 categoryLeft = TokenFrameContainerButton1CategoryLeft {
 }
 SetupPieceVisuals = <function> defined @Aurora/Skin/backdrop.lua:178
 SetBackdropColor = <function> defined @Aurora/Skin/backdrop.lua:275
 LeftEdge = Texture {
 }
 name = TokenFrameContainerButton1Name {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = 0
(*temporary) = <userdata>
(*temporary) = <function> defined @Aurora/Skin/backdrop.lua:400
(*temporary) = TokenFrameContainerButton1 {
 0 = <userdata>
 index = 1
 stripe = TokenFrameContainerButton1Stripe {
 }
 OnBackdropLoaded = <function> defined @Aurora/Skin/backdrop.lua:175
 GetBackdropColor = <function> defined @Aurora/Skin/b

### Expected Behavior

No error during login on when opening Currency Tab

### Steps To Reproduce

1. Open Currency Tab
2. Error appears

### Additional context

Appears with only aurora or with other addons loaded. Occurs with hooksecurefunc error on login. Also occurs when turning in quests.

**Comment by arnvid** [comment]
Closing this for now - am working on redoing the Classic/SOD/etc implementation. But for now I have disabled the packaging of these modules and closing the tickets related to this. Sorry I cannot update anymore at this time.  The wow-ui-sources are getting more in-line to make this a reality and thus why I am working on a restructure of all of these things.
